### ISSUE TITLE
Lüftungsposition beim HmIP-MOD-HO Hinzufügen

### ISSUE THREAD

**Issue by gerd2005** [thkl/hap-homematic#281]
@thkl 
wenn du gem. #257 eh an dem HmIP-MOD-HO etwas herumbastelst... könntest du vielleicht noch ein drittes Gerät hinzufügen der die Lüftungsposition aktiviert?

Bei einem Klick auf „Lüftungspostion“ fährt das Tor einige Zentimeter hoch. Um es wieder zu schließen muss man auf „Schließen“ klicken.

![E32742D1-39F3-46BB-B444-98FFC865C4BF](https://user-images.githubusercontent.com/72799068/102218169-deb48880-3edd-11eb-97dd-2dc91c5bc3e0.png)

Wäre es möglich das vielleicht analog zum Boost-Mode des HmIP-BWTH umzusetzen? Für den Boost-Mode wird ein Schalter in HomeKit angezeigt. Wäre für das Garagentor eine schöne Lösung.

![ACB2A955-44BB-4504-B49F-A60CF858A32A](https://user-images.githubusercontent.com/72799068/102218192-e5db9680-3edd-11eb-96e1-3dee81580bb1.png)

Lieben Gruß

**Comment by gerd2005** [comment]
.... Wobei... je länger ich drüber nachdenke, funktioniert das vermutlich gar nicht, da der Schalter mit der Lüftungsposition kein eigener Kanal ist, oder wie ist das...?

**Comment by thkl** [comment]
Hat der Aktor eine entsprechende Funktion ?

**Comment by gerd2005** [comment]
Ja, siehe roten Kringel.

![69BBBB29-C932-4542-887D-0253AB0EEBEF](https://user-images.githubusercontent.com/72799068/102222395-a87a0780-3ee3-11eb-8bf8-26b1b8f46d5c.jpeg)

**Comment by thkl** [comment]
Dann geht das

**Comment by gerd2005** [comment]
Ah ok. Dann wäre es schön, wenn du so einen Schalter einbauen könntest.
Vielen lieben Dank!

**Comment by thkl** [comment]
kurze Frage: was soll passieren wenn man den Lüften Modus ausschaltet ? Tor zu oder ?

**Comment by gerd2005** [comment]
Das wäre super, ja.

**Comment by flohei** [comment]
@thkl Kurze Verständnisfrage: Jetzt, wo du den Schalter für die Lüftungsposition eingebaut hast – was muss ich tun, damit ich den auch angezeigt bekomme. 

Ich habe mein HMIP-MOD-HO schon eine Weile für deine Lösung laufen. Super Sache, vielen Dank für deine Arbeit!

**Comment by thkl** [comment]
![Uploading image.png…]()

**Comment by meistermolli** [comment]
gilt dann sicher ab dem nächsten HAP Update?

**Comment by flohei** [comment]
Ich habe gerade das File aus dem o.g. Commit genommen und konnte damit bei mir das Häkchen für die Lüftungsposition setzen. Allerdings bekomme ich nun gar keinen Status mehr. In Home geht der Status von Updating sofort auf "No Response". Lass mich wissen, wenn ich dir irgendetwas zum Debuggen bereitstellen kann.

**Comment by thkl** [comment]
siehe https://github.com/thkl/hap-homematic/issues/294#issuecomment-751490985 ich hatte einen Tippfehler, der zum Crash führt. Dummerweise ist der beim Unit Test vor dem Commit nicht aufgefallen. Die neue Version läuft zumindest im Simulator problemlos.

**Comment by flohei** [comment]
Ah, perfekt. Danke für den Hinweis. Ich hab den Typo bei mir nun auch gefixt. Jetzt scheint es zu funktionieren. Danke!

**Comment by flohei** [comment]
Eine Beobachtung: Seit ich gestern auf die aktuellste Version gegangen bin und ich dein File händisch ausgetauscht habe, scheint das Plug-In immer wieder abzustürzen. Das äußert sich dann darin, dass HM-Geräte in Home.app und die Konfigurationswebsite nicht mehr erreichbar sind. 

Wenn ich den Neustart über RaspberryMatic triggere, sehe ich folgende Meldung:

![image](https://user-images.githubusercontent.com/192587/103197181-de58bc00-48e5-11eb-82aa-c4d383e49c1a.png)

Aber danach ist deine Software dann wieder erreichbar.

**Comment by thkl** [comment]
Liegen im /etc/config/addons/hap-homematic/ Ordner .crash Files ?

**Comment by flohei** [comment]
Jepp, ich habe zwei Crashlogs. Seit gestern habe ich auch zwei Crashes beobachtet. 

1:
```
Error log : Sun Dec 27 2020 18:41:29 GMT+0100 (CET)

TypeError: self.ldebugLog is not a function
    at On.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticGarageDoorOpenerAccessory.js:211:18)
    at On.emit (events.js:315:20)
    at On.EventEmitter.emit (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at On.Characteristic._this.setValue (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/Characteristic.js:338:23)
    at /usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/Accessory.js:940:36
    at Array.forEach (<anonymous>)
    at HAPServer.Accessory._this._handleSetCharacteristics (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/Accessory.js:808:18)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)
    at HAPServer._this._handleCharacteristics (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/HAPServer.js:840:23)
````

Und 2:

```
Error log : Mon Dec 28 2020 08:15:47 GMT+0100 (CET)                                
                                                                                   
TypeError: self.ldebugLog is not a function                                        
    at On.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticGarageDoorOpenerAccessory.js:211:18)                          
    at On.emit (events.js:315:20)                                                  
    at On.EventEmitter.emit (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)                                                  
    at On.Characteristic._this.setValue (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/Characteristic.js:338:23)                                   
    at /usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/Accessory.js:940:36                                                                           
    at Array.forEach (<anonymous>)                                                 
    at HAPServer.Accessory._this._handleSetCharacteristics (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/Accessory.js:808:18)                     
    at HAPServer.emit (events.js:315:20)                                           
    at HAPServer.EventEmitter.emit (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/EventEmitter.js:59:38)                                           
    at HAPServer._this._handleCharacteristics (/usr/local/addons/hap-homematic/node_modules/hap-nodejs/dist/lib/HAPServer.js:840:23)
```

**Comment by thkl** [comment]
Ah ja, das war ein Typo der es durch die automatischen Tests geschafft hat. Siehe https://github.com/thkl/hap-homematic/issues/294#issuecomment-751490985 ... in der aktuellen Version des Files hier ist das gefixt.

**Comment by flohei** [comment]
Ach, es gab zwei Vorkommen. Ich habe lediglich eins ausgebessert. Mein Fehler. Danke noch mal!

**Comment by schoe-to** [comment]
Egal wie oft ich es versuche, wenn ich den HmIP-MOD-HO einer Instanz hinzufügen will, erscheint es einfach nicht. Die Lüftungsposition sehe ich wie oben im Screenshot auch, aber das Gerät lässt sich nicht hinzufügen.

Kann mir jemand helfen? Würde die Garage echt gerne über Homekit bedienen können…
