### ISSUE TITLE
Komplettabsturz bei Anlegen einer Instanz

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/hap-homematic#380]
Ich habe eine dritte Instanz angelegt, danach dauerte es ewig, dann habe ich den Dienst neu gestartet jetzt werden gar keine Instanzen mehr angezeigt. Ich habe mich mal per SSH mit der CCU verbunden die config.json und andere json sind noch da. Das Log kann ich aber über das UI nicht herunterladen das wartet auch ewig.

**Comment by thkl** [comment]
bitte mal hier entlang dann sollte ggf ein Fehler auflaufen:

https://github.com/thkl/hap-homematic/wiki/Troubleshooting

**Comment by iuliusmaximilian** [comment]
Ich bekomme bei /usr/local/config/etc/rc.d/hap-homematic stop ein

# /usr/local/config/etc/rc.d/hap-homematic stop
-sh: /usr/local/config/etc/rc.d/hap-homematic: not found

**Comment by iuliusmaximilian** [comment]
etc und config ist in der Doku vertauscht, bekomme bei Start dann einen Error

```
[Thu Feb 25 2021 16:29:16 GMT+0100 (CET)] [HAP Server] [Server] did not find settings for special device with id f0e64609-5a94-4cba-83b1-bb0429cf9984:0
(node:2919) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Service' of undefined
    at Promise.all.special.map.spDevice (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:1200:31)
    at Array.map (<anonymous>)
    at Server._loadSpecialDevices (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:1190:15)
    at Server.loadInstance (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:534:15)
    at Promise.all.Object.keys.map.instanceID (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:338:27)
    at Array.map (<anonymous>)
    at Server.powerUpBridges (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:334:31)
    at Server.connectCCU (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:425:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:2919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by thkl** [comment]
kannst du mal die config.json posten da ist ein Fehler drin

**Comment by iuliusmaximilian** [comment]
Perfekt - habs gefunden, hab das Spezial Device per Hand raus geschmissen da ist was schief gelaufen. Danke!

**Comment by thkl** [comment]
ja, ich werd dafür sorgen, das beim nächsten Release das Problem nicht noch mal auftreten kann
