### ISSUE TITLE
Crashfile Installation Version 59

### ISSUE THREAD

**Issue by meistermolli** [thkl/hap-homematic#388]
Hi,
bei der installation von version 59 über den HAP Browser ist die HAP Homematic gecrasht.
Auch ein Neustart der CCU hat nichts gebracht.

Gruß meistermolli

root@homematic-raspi:/usr/local/etc/config/addons/hap-homematic# cat 1614719582548.crash

Error log : Tue Mar 02 2021 22:13:02 GMT+0100 (CET)

Error: write EPIPE
at ChildProcess.target._send (internal/child_process.js:807:20)
at ChildProcess.target.send (internal/child_process.js:678:19)
at Server.publishAccessoriesToConfigurationService (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:837:23)
at Server.connectCCU (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:428:12)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async Server.continueInitialization (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/Server.js:208:5)
root@homematic-raspi:/usr/local/etc/config/addons/hap-homematic#

**Comment by meistermolli** [comment]
Anschließend:

HAP gelöscht, Raspberrymatic Version 3.55.10.20210213 erneut drüber installiert.
HAP über installer 0.0.14 Installiert.

Erscheint leider nicht unter Zusatzsoftware.

**Comment by meistermolli** [comment]
Backup eingespielt der Raspberrymatic und da war dann wieder alles drauf.
Zusätzlich sogar Version 59 von HAP Installiert?

**Comment by thkl** [comment]
Das Plug-in wird immer in aktuellster Version installiert. 
Der Crash kommt von einem drunter liegenden Modul hmm ich schau mal ob ich das nachvollziehen kann.

**Comment by meistermolli** [comment]
Also es läuft wieder alles perfekt, war nur von dem Absturz bei der installation und dem Anlegen von dem Crashfile etwas irritiert.

**Comment by thkl** [comment]
Hmm ja leider kann ich an der Stelle nicht sehen, was ggf den Crash ausgelöst hat.

**Comment by meistermolli** [comment]
Dann machen wir hier mal zu.
