### ISSUE TITLE
Fehler beim aktualisieren des Triggers

### ISSUE THREAD

**Issue by cFire112** [thkl/hap-homematic#525]
Ich habe auf der CCU3 eine Systemvariable angelegt, deren Wert ich in Homekit anzeigen lassen möchte.

Beim Einrichten des Triggers wird trotz angehaktem "CCU Hilfsprogramm erzeugen/aktualisieren" kein Hilfsprogramm erstellt.

Das Logfile vom HAP zeigt folgenden Fehler:
```
[Thu Jan 27 2022 18:20:58 GMT+0100 (CET)] error - [HAP Server] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at HomeMaticCCU.updateCCUVarTrigger (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:624:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
woran könnte das liegen?

CCU3
Firmwareversion 3.61.7

**Comment by cFire112** [comment]
Jetzt hat es auf einmal geklappt...
Ich glaube der Fehler lag damit beim Datenaustausch mit der CCU.
