### ISSUE TITLE
HmIP-DLD bringt hap-homematic direkt zum Absturz

### ISSUE THREAD

**Issue by MNieddu91** [thkl/hap-homematic#571]
Sobald ich den Tüschlossantrieb in hap-homematic hinzufügen möchte stürzt wenige Sekunden danach das Plugin ab. Dies geschieht erst seit dem letzten Update der Raspberrymatic. Wurde hier vielleicht etwas geändert was die Datenpunkte betrifft ? 
Folgender Crashlog folgt nach jedem Absturz: 

```
TypeError: Cannot set properties of undefined (setting 'lockEvents')
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticKeyMaticIPAccessory.js:176:30
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:832:9
    at Array.map (<anonymous>)
    at HomeMaticCCU.fireEvent (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:831:14)
    at /usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/HomeMaticCCU.js:532:16
```
Der Fehler ist dauerhaft reproduzierbar. Sofern ich es schaffe in den 2-3 Sekunden solange das Plugin nach Neustart aktiv bleibt den Türschlossantrieb aus den Geräten zu entfernen läuft das Plugin wieder stabil. 

Es scheint hier ein Fehler in der HomeMaticKeyMaticIPAccessory.js Zeile 179 vorzuliegen, bzw. hat sich das Verhalten mit dem letzten Update der Raspberrymatic auf 3.65.11.20221005 dahingehend geändert ?!

Jedenfalls konnte ich den Fehler für mich temporär lösen, indem ich die Zeile 176 wie folgt verändert habe. 
self.self.lockEvents = false     ->     self.lockEvents = false

Kannst du dir das bitte einmal anschauen @thkl . Wundert mich ehrlich gesagt, dass sonst noch niemand den Fehler festgestellt hat.

**Comment by fittikus** [comment]
Ich habe den Fehler leider auch.
Habe das And-On extra wegen dem Türschloss installiert :-(
Ich würde mich total freuen, wenn der Fehler zeitnah gefixt wird.

**Comment by thkl** [comment]
Moin,

der Fehler ist in diesem File: lib/services/HomeMaticKeyMaticIPAccessory.js

an dieser Stelle:

https://github.com/thkl/hap-homematic/blob/2ba8a61a54743036884e9597668f83649bdeaf9c/lib/services/HomeMaticKeyMaticIPAccessory.js#L179

es muss heissen 
```
self.lockEvents = false 
```

**Comment by thkl** [comment]
https://github.com/thkl/hap-homematic/commit/7bba255e1d363d5730ccbfafe4eac3edfb71122b sollte das lösen

**Comment by fittikus** [comment]
Vielen Dank für die Hilfe!!!
Als Laie war das mein erstes Mal, dass ich mich getraut habe im Code was zu ändern. Hat ein bisschen gedauert, bis ich die Datei gefunden habe. Nach einem Neustart des Addons ist es wieder gelaufen.
Heißt das jetzt aber, dass bei der nächsten Version die Änderung gleich im Code mit dabei ist, oder?

**Comment by nItroTools** [comment]
@thkl Wann erscheint denn (u. a.) dazu ein neues Release? Das aktuelle Release v0.0.14 ist von 2020.
PS: Danke für die tolle Arbeit!

**Comment by blackbasket** [comment]
Das ist nur der Installer @nItroTools ... die eigentliche Version ist zwar auch schon was älter, aber 0.0.63, wenn ich es gerade richtig im Kopf habe... das siehst du in der WebUI des Plug-ins

**Comment by nItroTools** [comment]
@blackbasket Tatsächlich 🙈 Danke!
