### ISSUE TITLE
Probleme mit Version 3.65.11.20221005 - hängt sich auf nach Änderungen

### ISSUE THREAD

**Issue by kampfschlonz** [thkl/hap-homematic#575]
Nach hinzufügen von neuen Aktoren oder Anderung der Einstellung in hap-homematic, wird nicht mehr aktualisiert, dauert die Aktualisierung sehr lange bzw. starten hap-homematic gar nicht mehr neu. Erst mit einem Neustart der CCU3 startet auch wieder hap-homematic. 

Verhalten nur unter 3.65.11.20221005.

Bereits zweimal Downgrade auf 3.65.8.20220831 gemacht. Hier läuft hap-homematic problemlos. Aktualiert sehr schnell, alles bestens.

**Comment by mvondemhagen** [comment]
same here.

**Comment by blackbasket** [comment]
Könnt ihr das Verhalten mit Debug-Logging nachstellen und die Logs einmal hochladen?

**Comment by ralan1965** [comment]
Moin,
bei mir führt bereits das Update auf 3.65.11.20221005 bei unveränderter Konfiguration zum wiederholten Absturz von hap-homematic.
Ein Downgrade auf 3.65.8.20220831 behebt das Problem sofort.

Anbei mein Debug-Logging.
[hap-homematic-log.txt](https://github.com/thkl/hap-homematic/files/9909534/hap-homematic-log.txt)

**Comment by mvondemhagen** [comment]
Das Log scheint nach einem Reboot überschrieben zu werden, und ich komme nur nach einem Reboot der CCU3 daran. Zumindest hab ich gestern Abend Debugging eingeschaltet, und heute nach Absturz und Reboot sehe ich nur Log Entries ab Reboot... Überseh ich was?

**Comment by blackbasket** [comment]
@ralan1965 danke für das log
@mvondemhagen ja, das ist richtig... da das log in /tmp liegt, musst du es vor dem reboot sichern

könnt ihr mal bitte noch kurz schreiben, welche Version von CUxD ihr verwendet? ich vermute mal, da habt ihr kein Update/Downgrade durchgeführt? ich kann in den Logs auf Anhieb nichts erkennen... ich hoffe, dass @thkl da mehr Erfolg hat bzw ggf schon anhand der Release Notes von Jens eine Idee hat...

**Comment by blackbasket** [comment]
achso, und könnt ihr bitte mal den Fix aus #453 prüfen?

**Comment by mvondemhagen** [comment]
Ich verwende gar keinen CUxD.

**Comment by mvondemhagen** [comment]
> achso, und könnt ihr bitte mal den Fix aus #453 prüfen?

Du meinst damit, das Caching auszuschalten, korrekt?

**Comment by blackbasket** [comment]
Ja, genau...

**Comment by kampfschlonz** [comment]
Ich habe ein Upgrade (3x) auf 3.65.11.20221005 durchgeführt. hap neu installiert und Backup eingespielt. Änderungen durchgeführt und Abstürze erzwungen druch einfaches Bestätigen der vorhandenen Aktoren. Irgendwann stürzt hap ab und erst durch einen kompletten Neustart der CCU startet hap auch wieder.

CUxD Version 2.9.4

[hap-homematic.log](https://github.com/thkl/hap-homematic/files/9922915/hap-homematic.log)

hap läßt sich nun nicht mehr selbständig starten.

**Comment by mvondemhagen** [comment]
- Upgrade auf 3.65.11.20221005 gemacht
- Angepasste HomeMaticCCU.js aus #453 eingespielt
- Irgendeinen Aktor betätigt (hier: Raumthermostat)
- HAP schmiert ab und tut nichts mehr
- Neustart HAP via RaspMatic - Zusatzsoftware Panel funktioniert, mit Fehlermeldung

`start-stop-daemon: warning: killing process 1787: No such process
kill: you need to specify whom to kill`

- HAP crashes bei Betätigung eines Aktors, Crashlog sagt:
`Error log : Wed Nov 02 2022 23:52:30 GMT+0100 (CET)

TypeError: Cannot read properties of undefined (reading 'hue')
    at Hue.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticDimmerAccessory.js:149:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Logfile: [hap-homematic.log](https://github.com/thkl/hap-homematic/files/9924663/hap-homematic.log)

**Comment by ralan1965** [comment]
Ebenfalls CUxD Version 2.9.4.

**Comment by ralan1965** [comment]
> Ebenfalls CUxD Version 2.9.4.

Gestern habe ich die CUxD auf 2.10.0 geupdatet und  dann die Raspberry-Maticwieder auf die Version 3.65.11.20221005 hochgesetzt.
hap-homematic hängt sich wieder nach knapp 5 Minuten auf.

**Comment by ralan1965** [comment]
So,
habe erst die HM zurückgesetzt auf 3.65.8.20220831. In der hap-homematic wurden schon seit längerem fehlende Rauchmelde angemeckert. Die fehlen auch in der HM, also ein anderes Problem. Nach Restart, Cache löschen etc. lief die Hap wie bisher auch problemlos unter dieser HM-version.

Dann Update auf 3.65.11.20221005. nach ca. 5 wieder Crash der Hap.

Hier die letzen 5 Min. im Log.

[Sat Nov 05 2022 09:31:17 GMT+0100 (CET)] info - [HAP Server] [Server]Â hap-homematic instance HomeMatic_Keller Bad (12:34:56:36:68:E8) is running on port 9891.
[Sat Nov 05 2022 09:31:17 GMT+0100 (CET)] info - [HAP Server] [Server] Bridge Connections are up for 15 bridges
[Sat Nov 05 2022 09:32:09 GMT+0100 (CET)] info - [HAP Server] [Server] 63 compatible devices found
[Sat Nov 05 2022 09:33:08 GMT+0100 (CET)] info - [HAP Server] [Server] 63 compatible devices found
[Sat Nov 05 2022 09:34:12 GMT+0100 (CET)] info - [HAP Server] [Server] 63 compatible devices found
[Sat Nov 05 2022 09:34:59 GMT+0100 (CET)] info - [HAP Server] [Server] 63 compatible devices found
[Sat Nov 05 2022 09:35:32 GMT+0100 (CET)] info - [HAP Server] [Server] 63 compatible devices found
[Sat Nov 05 2022 09:36:10 GMT+0100 (CET)] info - [HAP Server] [Server] 63 compatible devices found
[Sat Nov 05 2022 09:36:20 GMT+0100 (CET)] error - [HAP Server] [RPC] Error while disconnecting interface HVL. Error : Error: getaddrinfo ENOTFOUND http
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http'
}

HVL nutze ich zur Verknüpfung nicht kompatibler HUE-Geräte, OSRAM-Zwischenstecker, mit HomeKit. Hat bisher auch immer einwandfrei funktioniert.

**Comment by blackbasket** [comment]
Also CUXD wird nichts damit zu tun haben... es muss offensichtlich an einer Änderung in der neusten RM-Version liegen... @thkl wird sich das sicher anschauen, wenn er Zeit hat... ggf. hätte auch Jens Maus eine Idee...

**Comment by thkl** [comment]
Moin,

Liegen im Config Verzeichnis ( /usr/local/etc/config/addons/hap-homematic ) vom hap irgendwelche .crash files ? Da wird normalerweise bei einem kompletten Crash des Daemons reingeschrieben, was schief gelaufen ist.

**Comment by thkl** [comment]
> `Error log : Wed Nov 02 2022 23:52:30 GMT+0100 (CET) TypeError: Cannot read properties of undefined (reading 'hue') at Hue.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/lib/services/HomeMaticDimmerAccessory.js:149:49) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5)`

Hier Crash eine Funktion die die Farbe eines HmIP-BSL in eine HomeKit verträgliche Version umrechnet.
Ggf hat sich da was in der RM geändert. Bitte mal testen, ob es immer noch crasht, wenn der HmIP-BSL aus der Configuration rausgenommen wird.

**Comment by ralan1965** [comment]
> Moin,
> 
**> Liegen im Config Verzeichnis ( /usr/local/etc/config/addons/hap-homematic ) vom hap irgendwelche .crash files ? Da wird normalerweise bei einem kompletten Crash des Daemons reingeschrieben, was schief gelaufen ist.**
> 
> Edit: So Update auf RM 3.65.11.20221005 und seit 20 Min keine Crashes ... Allerdings läuft die RM bei mir in einer ProxMox Umgebung. Aber HAP als Addon in der RM VM .... es scheint sich also ggf um ein Gerätespezifisches Problem zu handeln.

Hier mein .crash-File:
   Error log : Sat Nov 05 2022 09:36:20 GMT+0100 (CET)
   Error: getaddrinfo ENOTFOUND http
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

Für mich leider nicht sehr erhellend :(

**Comment by thkl** [comment]
Bitte mal im Debug Modus von der Shell aus starten (wie das geht steht hier im Wiki) es sieht aus wie dass auf ein Interface der CCU nicht connected werden kann.  Das erzeugt auch log Daten die brauch ich mal.

**Comment by ralan1965** [comment]
Sorry thkl. Habe nach meinem letzten Post direkt das HVL-Interface deinstalliert und im HAP die Geräte gelöscht. 
Das HVL-interface wurde bereits weiter oben in meinem Error-log angezeigt.

###[Sat Nov 05 2022 09:36:20 GMT+0100 (CET)] error - [HAP Server] [RPC] Error while disconnecting interface HVL. Error : Error: getaddrinfo ENOTFOUND http
at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'http'
}
###

Nun läuft HAP-HM seit bereits 20 Minuten einwandfrei im aktuellen Raspberry-Release.

Allerdings möchte ich auf die HVL-Geräte nicht im HomeKit verzichten. Werde heute nachmittag mal HVL neu installieren und die Geräte neu hinzufügen. Mal schau'n ob es so rum funzt.

Jetzt geht es erst mal in den Garten. Muss das gute Wetter nutzen ;)

**Comment by thkl** [comment]
Evtl wird der HVL Port ja durch die Firewall geblockt.  Das ist im Normalfall 7000

**Comment by blackbasket** [comment]
Kann es damit zu tun haben?

Aus den RM release notes:

replaced all static sleep X uses after loading required kernel modules (eq3_char_loop, etc.) with proper access checks using head -c0 which should help to deal way better with the dynamic device generation process, especially in case of using HomeAssistantOS as the based OS (cf. home-assistant/operating-system#2133 (comment)).

**Comment by ralan1965** [comment]
> Evtl wird der HVL Port ja durch die Firewall geblockt. Das ist im Normalfall 7000

Das hat leider auch nicht funktioniert.

HAP crasht unter HM 3.65.11.20221005 definitiv nur bei Geräten der HVL. Neuinstallation und -einrichtung von HVL nutzt nichts. Entfernt man die Geräte wieder, läuft wieder alles normal. Auch ohne Neustart.

Liegt womöglich am HM-Release, da bis zum Upgrade nie Probleme auftraten.

**Comment by thkl** [comment]
Wenn sich nichts in den Logs findet dann würde maximal ein Start von hap via SSH Commandline noch mehr Infos bringen.
Wie das geht, ist hier beschrieben: https://github.com/thkl/hap-homematic/wiki/Troubleshooting

Hier wird das komplette Log + Fehler in das Consolenfenster geschrieben ... ggf kommen wir da weiter.

**Comment by blackbasket** [comment]
@kampfschlonz nutzt du HmIP-BSL? @mvondemhagen hast du den HmIP-BSL testweise aus hap entfernt?

**Comment by tukkatakka** [comment]
Hallo,
ich habe ebenfalls das Verhalten: HAP stürtzt mit Version: 3.65.11.20221005 ab.
Wenn ich Änderungen über die HAP-WEB-Ui mache, stürtzt es sofort ab. Neustart auch nicht möglich. Einzig volles RapsberryMatic Backup wieder einspielen hilft, solange bis man wieder versucht in HAP Änderung zu machen. Spiele ich ein RaspberryMatic Backup mit Version: 3.65.8.20220831 ein, läuft HAP ohne Probleme und ich kann Änderungen durchführen. Zur Info: Zwischen den RaspberryMatic Versionen: 3.65.8.20220831 und 3.65.11.20221005 wurden keine Geräte Änderungen oder sonstige Änderungen durchgeführt.

**Comment by thkl** [comment]
Die Config Datei liegt hier : /usr/local/etc/config/addons/hap-homematic/config.json
Wenn nach dem Ändern nichts mehr geht, ist da ggf was schief gelaufen.
Was Du machen kannst: Sichere vor der Änderung einmal diese config.json Datei (zb lokaler Download).
Dann einmal die Änderung machen, die zum Crash führt ... hinterher ggf die alte config wieder einspielen.
Wenn Du dann hier noch die alte und neue (kaputte config) ablegst, kommt ich ggf hinter das Problem.

**Comment by ralan1965** [comment]
> Wenn sich nichts in den Logs findet dann würde maximal ein Start von hap via SSH Commandline noch mehr Infos bringen. Wie das geht, ist hier beschrieben: https://github.com/thkl/hap-homematic/wiki/Troubleshooting
> 
> Hier wird das komplette Log + Fehler in das Consolenfenster geschrieben ... ggf kommen wir da weiter.

Hier mal mein Debug-LOG mit Absturz. Was mir aufgefallen ist, das der Absturz ziemlich genau nach 5 Minuten eintritt. Und auch das der hap-server nach dem Start einen Watchdog für 5 Minuten startet. 
[hap-homematic-debug.log](https://github.com/thkl/hap-homematic/files/9945551/hap-homematic-debug.log)

**Comment by tukkatakka** [comment]
anbei die beiden Dateien. Ich konnte jetzt auch festestellen dass wohl das KeyMatic den Fehler auslöst.
Ich hatte ein RasperryMatic Backup eingespielt, und trotzdem lief HAP nicht an. Was sonst immer funktioniert hatte.
Crashlog habe ich auch angefügt. Im alten RaspberrryMatic 3.65.8.20220831 Backup, habe ich die Crashlogs nicht.
[crashlog.txt](https://github.com/thkl/hap-homematic/files/9945814/crashlog.txt)
[config_crash.txt](https://github.com/thkl/hap-homematic/files/9945815/config_crash.txt)
[config.txt](https://github.com/thkl/hap-homematic/files/9945816/config.txt)

**Comment by kampfschlonz** [comment]
Ich bin aktuell wieder auf 3.65.8.20220831, alles läuft bestens mit HAP. Ich warte jetzt erst einmal, ob ihr was in den aktuellen Logs findet. Ansonsten kann ich gerne nochmals ein Upgrade durchführen und Abstürze erzwingen um an neue Logs zu kommen. Gebt dann kurz bescheid.

**Comment by kampfschlonz** [comment]
@blackbasket ich habe keinen HmIP-BSL im Einsatz. Daran kann es nicht liegen.

**Comment by tukkatakka** [comment]
Wenn ich die RaspberryMatic neustarte und HAP nicht funktioniert und ich dann einmal am KeyMatic auf Aufschließen oder Abschließen drücke, läuft HAP an. Einstellungen in HAP führen trotzdem zum Crash.

**Comment by kampfschlonz** [comment]
@tukkatakka KeyMatic = HmIP-DLD?

**Comment by tukkatakka** [comment]
@kampfschlonz ja genau

**Comment by kampfschlonz** [comment]
@tukkatakka ok, die KeyMatic habe ich auch. Dann sollten wir mal schauen ob da das Problem liegt. Werde mal ein Upgrade durchführen, die KeyMatic vorher rausschmeißen und dann prüfen.

**Comment by tukkatakka** [comment]
Ich konnte es hiermit lösen >  https://github.com/thkl/hap-homematic/issues/571

**Comment by meibner** [comment]
@tukkatakka @thkl Bei mir stürtze das AddOn auch immer ab, mit #571 konnte ich das Problem nur auf 5 Minuten verlängern. Ich hab das AddOn mal über SSH gestartet und aufgrund der Fehlermeldung dann das HVL Addon entfernt.. wäre zwar schön, wenn es wieder geht. Aber so funktioniert HAP nun aktuell bei mir.

Hier meine Fehlermeldung aus dem SSH:
`
[Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP Server] [RPC] Watchdog Trigger - Reinit Connection for HVL. after idle time of 310 seconds
[Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP Server] [RPC] disconnecting interface HVL.
[Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP Server] [RPC] CCU RPC Init Call on http port null for interface HVL. local server port 9875
[Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP Server] [RPC] init parameter is http://192.168.86.24:9875 HAP_HVL.
[Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP Server] [RPC] Error while disconnecting interface HVL. Error : Error: getaddrinfo ENOTFOUND http
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http'
}
[Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP Server] uncaughtException  log will be found in /usr/local/etc/config/addons/hap-homematic/1667818452681.crash exiting now
Error: getaddrinfo ENOTFOUND http
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
root@homematic-raspi:/# [Mon Nov 07 2022 11:54:12 GMT+0100 (CET)] [HAP ConfigServer] [Config] Shutdown Configuration Service
`

**Comment by thkl** [comment]
> @tukkatakka @thkl Bei mir stürtze das AddOn auch immer ab, mit #571 konnte ich das Problem nur auf 5 Minuten verlängern. Ich hab das AddOn mal über SSH gestartet und aufgrund der Fehlermeldung dann das HVL Addon entfernt.. wäre zwar schön, wenn es wieder geht. Aber so funktioniert HAP nun aktuell bei mir.

Es schaut so aus, als ob HAP keine URL für das HVL Interface von der CCU bekommt. Da muss ich mal einen Workaround bauen um ggf die Interfacedaten aus der Config.json zu lesen ...

**Comment by tukkatakka** [comment]
Zur Info: Bei mir läuft HAP nach der Änderung > https://github.com/thkl/hap-homematic/issues/571 nun wieder ohne Probleme.
neue Geräte erstellen, CCU3 neustart, WEB-UI alles funktioniert wieder wie es soll. 

Sorry, HVL Addon war bei mir nie installiert!

**Comment by kampfschlonz** [comment]
@tukkatakka ok, dann führe ich das auch mal durch und berichte. Danke für die Info!

**Comment by kampfschlonz** [comment]
Auch bei mir läuft HAP nach der Änderung #571 nun wieder ohne Probleme.

**Comment by ralan1965** [comment]
Hallo zusammen,
habe heute mal ein rudimentäres RaspberryMatic Version 3.65.11.20221005 aufgesetzt. Erst HVL installiert, einen OSRAM-Zwischenstecker über das HUE-Plugin installiert. Lässt sich oh. Probleme in der RM bedienen.
Dann hap-homematic installiert, eine Instanz mit zugehöriger Portfreigabe erzeugt. hap läuft ohne Probleme mehr als 5 Minuten. Dann den o.g. OSRAM-ZwSt gemappt. Wird auch in der Apple Home-App angezeigt und ist auch bedienbar.

Nach ca. 5 Minuten schmiert hap-homematic wieder ab. Und zwar genau dann, wenn der Watchdog den HVL neu starten will:

[Sat Nov 12 2022 18:18:00 GMT+0100 (CET)] debug - [HAP Server] [RPC] Watchdog Trigger - Reinit Connection for HVL. after idle time of 310 seconds
[Sat Nov 12 2022 18:18:00 GMT+0100 (CET)] debug - [HAP Server] [RPC] disconnecting interface HVL.
[Sat Nov 12 2022 18:18:00 GMT+0100 (CET)] debug - [HAP Server] [RPC] CCU RPC Init Call on http port null for interface HVL. local server port 9875
[Sat Nov 12 2022 18:18:00 GMT+0100 (CET)] debug - [HAP Server] [RPC] init parameter is http://192.168.0.59:9875 HAP_HVL.
[Sat Nov 12 2022 18:18:00 GMT+0100 (CET)] debug - [HAP Server] [RPC] CCU Response for init at HVL. with command http://192.168.0.59:9875,HAP_HVL. ...Value (undefined) Error : (Error: getaddrinfo ENOTFOUND http
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http'
})
[Sat Nov 12 2022 18:18:00 GMT+0100 (CET)] error - [HAP Server] [RPC] Error while disconnecting interface HVL. Error : Error: getaddrinfo ENOTFOUND http
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'http'
}

Anbei noch das gesamte LOG
[hap-homematic.log](https://github.com/thkl/hap-homematic/files/9995778/hap-homematic.log)

**Comment by ChrWi** [comment]
Ich nutze 3.65.11 mit piVCCU 3 / ohne RM. Derartige Probleme habe ich nicht, wobei die 3.65.11 nicht sauber zu sein scheint, vgl. https://homematic-forum.de/forum/viewtopic.php?f=69&t=75886&p=739632#p739632

**Comment by ralan1965** [comment]
> Ich nutze 3.65.11 mit piVCCU 3 / ohne RM. Derartige Probleme habe ich nicht, wobei die 3.65.11 nicht sauber zu sein scheint, vgl. https://homematic-forum.de/forum/viewtopic.php?f=69&t=75886&p=739632#p739632

n'Abend. Der Verdacht, dass die Probleme mit dem RM-Update auf 3.65.11 zusammenhängen, wurde hier schon mal geäußert, da sie erst nach dem Update auftraten - bei unveränderter Konfiguration.

**Comment by kampfschlonz** [comment]
Hallo zusammen,

leider ist das Problem nach wie vor vorhanden. Habe heute zei HmIP-SWDO-I Fensterkontakte neu in die CCU3 angelernt. Beim anlegen in HAP stürzte jedesmal HAP ab. Erst ein CCU Neustart konnte HAP auch wieder zum laufen bringen.
HVL benutze ich nicht, daran kann es nicht liegen.

Anbei ein Auszug aus dem chrsh file - sind beide identisch:

Error log : Wed Nov 16 2022 13:46:03 GMT+0100 (CET)

Error: XML-RPC fault: Transmission is pending.
    at createFault (/usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:83:21)
    at Deserializer.onDone (/usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:89:21)
    at SAXStream.emit (node:events:527:28)
    at SAXParser.SAXStream._parser.onend (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:363:3)
    at SAXParser.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:209:16)
    at IncomingMessage.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:641:28)

**Comment by Gandalf1-1** [comment]
Habe ebenfalls das Problem, dass sich der HAP nach wenigen Minuten unter Version 3.65.11.20221005 aufhängt. Die HAP Oberfläche ist dann gar nicht mehr zu erreichen.
Ebenfalls bereits dreimal Downgrade auf 3.65.8.20220831 gemacht. Hier läuft der hap-homematic problemlos.

**Comment by mike4president** [comment]
ich hab das gleiche Problem. Bei mir läuft das Ganze jetzt in einer virtuellen Maschine in TrueNas. HAP schmiert immer wieder ab. Ich wollte erst das Raspberrymatic Aden in Home Assistant nutzen, aber da geht HAP ja leider gar nicht. Heul, Schluchtz, Zeter, auf den Boden stampf

**Comment by Gandalf1-1** [comment]
habe den NightlyBuild 20221125 getestet, das gleiche problem.

**Comment by Gandalf1-1** [comment]
Habe mit dem nigthly Build 20221125 getestet, zuerst war ich noch auf der Lan Verbinung, da hatte ich zuerst das Gleiche verhalten wie unter 221205. 
-> Alle Geräte in der Hommatic GUI sichtbar - nach aufruf des Hubs hängt das System.
Nachdem ich dann auf WLAN gestartet hatte, (andere IP unter der er normalerweise läuft) ging zuerst alles, auch der HUP. Nach dem nächsten Neustart waren dann gar keine Geräte mehr in der homematic GUI sichtbar, es wurde auch kein Duty Cycle weder vom der CC noch von den Accespoints dargestellt. Der Hup lässt sich aufrufen zeigt aber ebenfalls keine Geräte. 
Mehrfach gestartet gleiches Ergebnis. 
Bei der Karte mit 20220831 scheint alles stabil zu sein.
