### ISSUE TITLE
[HAP Server] uncaughtException - Crash alle paar Minuten 

### ISSUE THREAD

**Issue by loki-sft** [thkl/hap-homematic#582]
RaspiMatic Firmwareversion: | 3.65.11.20221005
hap-homemartic 0.0.14

Auszug aus Log:
`[Sun Nov 13 2022 23:13:51 GMT+0100 (CET)] info - [HAP Server] [Server] seems we are stable since 1 hour remove the restart counter
[Sun Nov 13 2022 23:13:51 GMT+0100 (CET)] info - [HAP Server] [CCU] disable Monitoring
[Mon Nov 14 2022 02:11:41 GMT+0100 (CET)] error - [HAP Server] uncaughtException  log will be found in /usr/local/etc/config/addons/hap-homematic/1668388301761.crash exiting now
`
Auszug aus Crash:
`Error log : Mon Nov 14 2022 02:11:41 GMT+0100 (CET)

Error: send ENETUNREACH 224.0.0.251:5353
    at doSend (node:dgram:705:16)
    at defaultTriggerAsyncIdScope (node:internal/async_hooks:465:18)
    at afterDns (node:dgram:651:5)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)`

mich irritiert die IP Adresse und der Port im Crash-log
224.0.0.251:5353

**Comment by blackbasket** [comment]
Also zum Fehler kann ich dir jetzt nicht direkt was sagen... aber das IP Range 224... ist für MultiCast, also hier richtig

**Comment by jb-home** [comment]
Auf was läuft die RaspberryMatic denn?
Direkt auf einer Hardware oder als VM?

**Comment by loki-sft** [comment]
> Auf was läuft die RaspberryMatic denn? Direkt auf einer Hardware oder als VM?

RaspiMatic läuft direkt auf einem RPi4
Jetzt bin ich auf Firmwareversion  3.65.11.20221218

aktuell steht in der Crashlog:
`Error log : Thu Dec 29 2022 16:26:35 GMT+0100 (CET)

Error: Unexpected end
Line: 0
Column: 0
Char: 
    at error (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:352:8)
    at end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:359:32)
    at SAXParser.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:209:16)
    at IncomingMessage.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by jb-home** [comment]
Da scheint wohl ein Fehler in der Konfigurationsdatei zu sein.
SAX ist ein Parser der anscheinend die Datei nicht komplett auswerten kann.
Überprüf mal ob die folgenden Dateien valides JSON Format haben:
/usr/local/etc/config/addons/hap-homematic/config.json
/usr/local/etc/config/addons/hap-homematic/devices.json
/usr/local/etc/config/addons/hap-homematic/evdps.json
/usr/local/etc/config/addons/hap-homematic/programs.json
/usr/local/etc/config/addons/hap-homematic/rooms.json
/usr/local/etc/config/addons/hap-homematic/variables.json

Kannst du z.B. hier: https://jsonlint.com

**Comment by loki-sft** [comment]
Alle 6 Files sind "valid". Soll ich sie Dir mal zur Verfügung stellen?

**Comment by ChrWi** [comment]
Ich mach mal zu, da seit 3 Jahren keine Rü
