### ISSUE TITLE
HAP ist nach hinzufügen eines Geräts nicht mehr erreichbar und startet auch nicht mehr

### ISSUE THREAD

**Issue by HookHM** [thkl/hap-homematic#591]
Hallo @thkl ,

ich habe in HAP ein Gerät (eine Virtuelle CCU Taste) einer Instanz hinzugefügt und dabei ist HAP wohl abgestürzt. Ein Neustart in der WebUI bei Zusatzsoftware gibt zwar das aus:
<img width="455" alt="Bildschirm­foto 2022-12-11 um 08 45 13" src="https://user-images.githubusercontent.com/55434236/206892108-256b585f-73dd-42e0-af8b-a277a70c9090.png">
Aber HAP ist weiterhin nicht erreichbar. Was kann ich jetzt tun, damit HAP wieder läuft und wo kann man das nachsehen damit ich es hier posten kann warum HAP nach hinzufügen des Geräts abgeschmiert ist?

**Comment by tzahari** [comment]
Ich habe das gleiche Problem mit einem Fensterkontakt.
Man kann dan HAP per Homeatic neustarten und dann geht es auch wieder.

Im Logfile ist folgendes zu finden:
```
[Sat Dec 17 2022 17:02:32 GMT+0100 (CET)] info - [HAP Server] [Server] reloading all appliances
[Sat Dec 17 2022 17:02:32 GMT+0100 (CET)] info - [HAP Server] [Server] shutting down Homekit bridge HomeMatic default
[Sat Dec 17 2022 17:02:33 GMT+0100 (CET)] info - [HAP Server] [Server] config loading completed; start building servicetable
[Sat Dec 17 2022 17:02:33 GMT+0100 (CET)] info - [HAP Server] [Server] service loading completed; publishing services
 
[Sat Dec 17 2022 17:02:35 GMT+0100 (CET)] info - [HAP Server] [Server] Your Bridge ID HomeMatic_default PinCode is XXX-XX-XXX
[Sat Dec 17 2022 17:02:35 GMT+0100 (CET)] info - [HAP Server] [Server] publishing accessories
[Sat Dec 17 2022 17:02:35 GMT+0100 (CET)] info - [HAP Server] [Server] 64 compatible devices found
[Sat Dec 17 2022 17:02:35 GMT+0100 (CET)] info - [HAP Server] [Server] hap-homematic instance HomeMatic_default (12:34:56:4e:40:ca) is running on port 9877.
[Sat Dec 17 2022 17:02:36 GMT+0100 (CET)] error - [HAP Server] [RPC] Error while sending command reportValueUsage to interface HmIP-RF. Error : Error: XML-RPC fault: Transmission is pending.
    at createFault (/usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:83:21)
    at Deserializer.onDone (/usr/local/addons/hap-homematic/node_modules/homematic-xmlrpc/lib/deserializer.js:89:21)
    at SAXStream.emit (node:events:527:28)
    at SAXParser.SAXStream._parser.onend (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:171:8)
    at emit (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:325:33)
    at end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:363:3)
    at SAXParser.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:137:24)
    at SAXStream.end (/usr/local/addons/hap-homematic/node_modules/sax/lib/sax.js:209:16)
    at IncomingMessage.onend (node:internal/streams/readable:693:10)
    at Object.onceWrapper (node:events:641:28) {
  code: -10,
  faultCode: -10,
  faultString: 'Transmission is pending.'
}
```

**Comment by HookHM** [comment]
Bei mir ging es leider garnicht HAP in der CCU WebUI unter der Zusatzsoftware neu zu starten. Bei mir war ein kompletter Neustart der CCU nötig damit HAP wieder hoch kommt. Hast Du eine Idee @thkl

**Comment by HookHM** [comment]
@thkl machst du noch etwas an HAP? HAP funktioniert derzeit wieder nicht mehr Neustart mit  selbiger Meldung wurde angeblich ausgeführt aber HAP ist nicht erreichbar. HAP scheint diesmal einfach so abgestürzt zu sein, denn ich habe nichts gemacht.

**Comment by ChrWi** [comment]
Was habt ihr an System und Zusatzsoftware?
Virtuelle Taster habe ich auch, aber nicht solche Probleme, insb xmlrpc

**Comment by ChrWi** [comment]
Sofern noch Bedarf besteht bitte ins erweiterte https://github.com/thkl/hap-homematic/wiki/Troubleshooting im Wiki schauen.
