### ISSUE TITLE
Geräte werden nicht zu HomeKit hinzugefügt

### ISSUE THREAD

**Issue by Tomtino1** [thkl/hap-homematic#621]
Hallo,

Seit dem update auf iOS 16.4 mit der neuen HomeKit-Architektur habe ich das Problem, dass die in der HAP-Homematic hinzugefügten Geräte nicht in Apples Hoomekit übernommen werden. Häufig findet es dann auch eine zeitlang keinerlei über HAP-Homematic hinzugefügte Geräte (keine Antwort).

Kann jemand dieses Problem bestätigen bzw. mir einen Tip geben, wie ich hier Abhilfe schaffen kann?

Ich nutze eine CCU3 und HAP-Homematic in der Version 0.0.14.

Vielen Dank im Voraus für eure Hilfe.

**Comment by mbgong** [comment]
Ich habe das Problem aktuell ausschließlich mit der Wetterstation Basic. Diese wird aber nicht einmal im HAP Plugin angelegt.

**Comment by Tomtino1** [comment]
Bei mir legt er alles brav im HAP-Plugin an, veröffentlicht es aber leider nicht im HomeKit. Schalter u.ä. Kannst du aber ins HomeKit bringen? @mbgong

**Comment by mbgong** [comment]
Ja genau, alles andere funktioniert.

**Comment by ChrWi** [comment]
Welche HomeKit Version?

**Comment by Tomtino1** [comment]
Nein, sie sind auch nicht im Standardraum

**Comment by ChrWi** [comment]
Hm, merkwürdig. Ich hatte mit 16.2 auf die neue HomeKit Architektur gewechselt (bevor Apple zurückgezogen hatte). Bis auf den Standardraum keine Probleme bzw. Auffälligkeiten

**Comment by Tomtino1** [comment]
Ja, ich weiß mir leider auch keinen Rat mehr 🙁

**Comment by ChrWi** [comment]
Ggf die Logs der hap-Homematic analysieren? Siehe Wiki oder andere Beiträge 
Hast du an der CCU was geändert (neue Firmware, neue Add-ons,…)?

**Comment by Tomtino1** [comment]
Ja, auf der CCU habe ich eine neue Firmware aufgespielt

**Comment by roe1974** [comment]
Welche Version der CCU bzw. RM läuft bei Dir ?

**Comment by jhk3** [comment]
Ich habe ähnliche Erfahrungen gemacht, mit iOS 16.4.1 mit dem Homekit Update. Bei mir hat sich das hier beschriebene Problem immer dann bemerkbar gemacht, wenn die bestehende Bridge, zu der ein neues Gerät hinzugefügt werden sollte, bereits einen Gerätekanal mit Abfrage von Energiedaten enthielt, z.B. Abfrage von HMIP-PSM kanal 6 oder HMIP-BSM Kanal 7.

**Comment by roe1974** [comment]
Welche Version der CCU bzw. RM läuft bei Dir ?

**Comment by jhk3** [comment]
> Die Ursache dafür, dass andere neu importierte Geräte nicht mehr angezeigt werden, kann dies zumindest bei mir nicht sein, da ich auch in eine völlig leere Bridge ein Import ins HomeKit nicht möglich ist.

Hmm, ich konnte keine Bridge hinzufügen, solange nicht mindestens ein Gerät der Bridge zugeordnet war und im Addon HAP-Homematic der "Published Devices" in der Liste der Instances/Bridges nicht auf "yes" stand.

**Comment by Tomtino1** [comment]
Jetzt wird es verworren :) Esfunktioniert bei mir auch auf 2 verschiedenen CCU´s in verschiedenen Homes nicht. Blöderweise bei beiden nahezu zeitgleich beides mit Updates versorgt

**Comment by jhk3** [comment]
RM 3.67.10.20230225 verwende ich auch (auf Tinkerboard S), aber iOS habe ich auf 16.4.1 aktualisiert, mit dem Architektur-Update. Ich vermute mal, dass es durch das Architektur-Update nicht mehr zu 100% kompatibel ist.

**Comment by roe1974** [comment]
PS: 16.4.1 habe ich auch, aber eben ohne dem Architektur Upgrade ...

**Comment by roe1974** [comment]
Seit heute gibt es TvOS 16.4.1 und 16.4.1 für HomePod ... ändert das etwas ?

**Comment by jhk3** [comment]
Gerade upgedatet, aber auch nach dem Update meines Apple TV4k2 auf 16.4.1 sehe ich keine Änderung am Verhalten meiner Geräte bzw. von Homekit und von der RM mit Addon.

**Comment by hardl1** [comment]
Seit einigen Tagen kann ich einen HMIP-SWD, einen HMIP-PSM und eine HMIP-DLS nicht mehr zu Homekit hinzufügen.
Alle Geräte waren schon integriert und haben in Homekit funktioniert.
RaspberryMatic V. 3.69.7.20230506 auf QNAP-VM
HAP-Homematic V. 0.0.63
APPLE-TV 4K V. 16.4.1
HomePod mini V. 16.4.1
In RaspberryMatic sind die Geräte vorhanden.
In HAP-HomeMatic werden alle Geräte unter Instanzen-Veröffentlichte Geräte als "nein" bezeichnet, 
unter Geräte-Instanz sind sie grau hinterlegt.
Bei Homekit sind die Bridges vorhanden, aber alle ohne Geräte
Ich habe mehrmals gelöscht, neu hinzugefügt, neu gestartet, neue Instanzen angelegt, die Geräte zurückgesetzt, leider ohne Erfolg.

**Comment by ChrWi** [comment]
Habe heute einen neuen HmIP-PS-2 angelernt. War nach 5min in Apple Home eingerichtet und funktioniert.
pivccu3.69.7, HomePod mini 16.5b
@thkl der HmIP-PS-2 kann im Gegensatz zum älteren HmIP-PS nicht als Typ Steckdose dargestellt werden.

**Comment by blackbasket** [comment]
> Habe heute einen neuen HmIP-PS-2 angelernt. War nach 5min in Apple Home eingerichtet und funktioniert.
> 
> pivccu3.69.7, HomePod mini 16.5b
> 
> @thkl der HmIP-PS-2 kann im Gegensatz zum älteren HmIP-PS nicht als Typ Steckdose dargestellt werden.
> 
> 

Poste mal bitte das Device File dazu...

**Comment by ChrWi** [comment]
> > Habe heute einen neuen HmIP-PS-2 angelernt. War nach 5min in Apple Home eingerichtet und funktioniert.
> > pivccu3.69.7, HomePod mini 16.5b
> > @thkl der HmIP-PS-2 kann im Gegensatz zum älteren HmIP-PS nicht als Typ Steckdose dargestellt werden.
> 
> Poste mal bitte das Device File dazu...

#630 

(brauchte etwas, das "Unautorized" beim Versuch, die Gerätedatei zu erzeugen, zu interpretieren. Lag daran, dass bei mir die CCU-Anmeldung eingeschaltet war)

**Comment by ChrWi** [comment]
iOS/tvOS 16.5 ist ja jetzt offiziell raus - merkt da jemand einen Unterschied bzgl. des Themas?

**Comment by hardl1** [comment]
Nach mehrmaligem Löschen aus allen Verbindungen und Rücksetzen auf Werkseinstellungen konnte ich jetzt alle Geräte in Home integrieren, allerdings ist IOS 16.5 noch nicht installiert.

Mir fehlt nur noch der Türschlosssensor HmIP-DLS, der von der HAP-Homematic nicht erkannt wird.
Ticket in Github-Issue ist erstellt.

**Comment by maroony** [comment]
Ich kann auch scheinbar keine Geräte mehr hinzufügen. Jedenfalls taucht im Moment weder ein Bewegungsmelder, noch mein virtueller Schalter in Home auf, den ich versucht habe hinzuzufügen. Alle meine Apple Geräte: Apple TV, Homepods usw. sind auf 16.5, die CCU auf 3.69.7.

**Comment by ChrWi** [comment]
@roe1974 @Tomtino1 bei Euch noch soweit alles ok? Falls ja - so wie bei mir - kann ich kein Fehlermuster erkennen: CCU 3.69.7, HAP-homematic unverändert, Apple zwischen 16.x und 16.y
Bei @hardl1 geht es nach dem Zurücksetzen wieder
Mit den Energie-Parametern nach Architektur-Upgrade kann es zu tun haben.
Jemand ne Idee?

**Comment by roe1974** [comment]
Ja bei mir geht alles normal ... alle Apple Geräte auf 16.5 ... Raspberrymatic 3.69.7.20230506 ... jedoch **ohne** Homekit Architektur Update :-)

**Comment by ChrWi** [comment]
HAP     CCU                  OS         Status
@ChrWi       neu     3.69.7 pivccu   16.6b.    nichts aufälliges, HAP update mit/vor 16.2
@roe1974    alt       3.69.7 RM         16.5.      alles normal, ohne HAP update
@hardl1       neu     3.69.7 RM         16.4.1     nach reset ok
@Tomtino1 
@maroony              3.69.7 RM         16.5.      keine neuen Geräte möglich
@jhk3           neu    3.67.10 RM.       16.4.1.

**Comment by thkl** [comment]
Mahlzeit,

Ich benutze nur noch sehr wenige CCU Geräte, daher ist es ein wenig ruhig mit der hap Entwicklung. 

Aber: ich hatte einige Probleme seit dem Update von HomeKit auf die neue Infrastruktur. Geräte wurden als non responding angezeigt. 

Lösung war ein Update von hap-nodejs (das ist das Framework was ich für die Kommunikation zu HomeKit benutze)

Man könnte hap-nodejs manuell via ssh auf die ccu aktualisieren.

Das Problem mit einem neuen Versionspaket ist: ich habe den kompletten ConfigUI Teil vor irgendwas mehr als einem Jahr weggeworfen und neu gemacht. Allerdings hab ich wenig Möglichkeiten zum Test, ob das Update alle Einstellungen übernimmt. 

Wenn jemand freiwillig das ausprobieren möchte, könnte ich ein Beta Update zur manuellen Installation packen.

**Comment by roe1974** [comment]
Hi Thomas, schön wieder von Dir zu lesen ;-)
Hättest Du eine Anleitung für das hap-nodejs Update via SSH ?
lg Richard

**Comment by thkl** [comment]
Das weiss ich nicht, aber ich denke schon. Die 0.5.7 Version, die mit Hap installiert wurde, ist halt auch schon 2 Jahre alt.

**Comment by roe1974** [comment]
... und wie kann man die Version überprüfen ... also ob das update geklappt hat ?

**Comment by thkl** [comment]
Das sagt dir npm i .... .. + ein bissel Geheule über security vulnerabilities in Paketen, die benutz werden. (Ich muss wohl wirklich mal ein neues npm Paket bauen .. ) .. Freiwillige Tester ?

**Comment by roe1974** [comment]
stimmt ... npm list im ordner bringt aktuell:
hap-homematic@0.0.63 /usr/local/addons/hap-homematic/node_modules/hap-homematic
+-- UNMET DEPENDENCY binrpc@3.3.1
+-- UNMET DEPENDENCY chalk@^4.0.0
+-- UNMET DEPENDENCY commander@^5.1.0
+-- UNMET DEPENDENCY expect.js@0.3.1
+-- UNMET DEPENDENCY fakegato-history@^0.5.6
+-- UNMET DEPENDENCY formidable@^1.2.2
+-- UNMET DEPENDENCY hap-nodejs@^0.5.7
+-- UNMET DEPENDENCY homematic-xmlrpc@1.0.2
+-- UNMET DEPENDENCY husky@^4.2.5
+-- UNMET DEPENDENCY mocha@^7.0.1
+-- UNMET DEPENDENCY moment@2.29.0
`-- UNMET DEPENDENCY sockjs@^0.3.20

npm ERR! code ELSPROBLEMS
npm ERR! missing: binrpc@3.3.1, required by hap-homematic@0.0.63
npm ERR! missing: chalk@^4.0.0, required by hap-homematic@0.0.63
npm ERR! missing: commander@^5.1.0, required by hap-homematic@0.0.63
npm ERR! missing: expect.js@0.3.1, required by hap-homematic@0.0.63
npm ERR! missing: fakegato-history@^0.5.6, required by hap-homematic@0.0.63
npm ERR! missing: formidable@^1.2.2, required by hap-homematic@0.0.63
npm ERR! missing: hap-nodejs@^0.5.7, required by hap-homematic@0.0.63
npm ERR! missing: homematic-xmlrpc@1.0.2, required by hap-homematic@0.0.63
npm ERR! missing: husky@^4.2.5, required by hap-homematic@0.0.63
npm ERR! missing: mocha@^7.0.1, required by hap-homematic@0.0.63
npm ERR! missing: moment@2.29.0, required by hap-homematic@0.0.63
npm ERR! missing: sockjs@^0.3.20, required by hap-homematic@0.0.63

**Comment by ChrWi** [comment]
Grundsätzlich würde ich da mit testen. Wenn ich aber per ssh auf meine piVCCU gehe und npm ausführe würde ich eine Fehlermeldung erhalten, dass die Platte read-only list. Muss da mal einsteigen - nach einem Backup.

**Comment by roe1974** [comment]
also hat das update via ssh funktioniert ?

**Comment by thkl** [comment]
Einfach mal hap beim Arbeiten zuschauen und schauen wo es Crasht

https://github.com/thkl/hap-homematic/wiki/Troubleshooting

Punkt 3 ist das StartCommand ...

**Comment by thkl** [comment]
BTW: Rollback von hap-nodejs:

```
cd /usr/local/addons/hap-homematic/node_modules/hap-homematic
npm i hap-nodejs@0.5.7
```

**Comment by ChrWi** [comment]
```
# node /usr/local/addons/hap-homematic/node_modules/hap-homematic/index.js
AssertionError [ERR_ASSERTION]: The cipher 'chacha20-poly1305' is not supported with your current running nodejs version vv8.11.4. At least a nodejs version of v10.17.0 (excluding v11.0 and v11.1) is required!
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/node_modules/hap-nodejs/src/lib/util/hapCrypto.ts:8:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/hap-homematic/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:11:1)
    at Module._compile (module.js:652:30)
# 
```

**Comment by ChrWi** [comment]
nodejs version vv8.11.4 ?? das ist doch auch uralt

**Comment by ChrWi** [comment]
OK, passt. Meine Homebridge Instanz (direkt auf dem Raspi) hat auch 16.18
Ich mache mal ein Rollback

**Comment by ChrWi** [comment]
Das Rollback funktioniert 1a. Konfig-Seite wieder da, alle Geräte im Apple Home haben geantwortet.

**Comment by jhk3** [comment]
Im Homematic Forum wird erwähnt, dass ein Addon (Nodered bzw Redmatic) sein eigenes nodejs mitbringt, da eq3 releases langsamer wären, als nodejs releases:

https://homematic-forum.de/forum/viewtopic.php?t=46019

(Vorletzter Beitrag auf der Seite). Ich habe allerdings nicht genug Einblick, um den Aufwand dafür einschätzen zu können.

Viele Grüße,

   Jörg

**Comment by ChrWi** [comment]
Bei eq3 es ist weiterhin 8.11.4

**Comment by thkl** [comment]
> Bei eq3 es ist weiterhin 8.11.4

Oh jeh ;/

**Comment by roe1974** [comment]
Auf der RM ist Node 16.18.1
Da müsste das aktuelle NodeJS funktionieren ... richtig ?

**Comment by thkl** [comment]
Ich hab die Info oben aktualisiert. Alles > 11.1 ist im Prinzip Ok.

**Comment by roe1974** [comment]
Ok ;-) ... npm lassen oder hochziehen ? (aktuell 8.19.2)

**Comment by ChrWi** [comment]
Entweder einfach probieren wie ich zuvor oder ggf Jens Maus fragen ob er eine Empfehlung hat

**Comment by roe1974** [comment]
kommen die zahlen hinter der Instanz jetzt durch das update oder war das immer schon da ?
<img width="825" alt="Bildschirmfoto 2023-05-24 um 19 35 57" src="https://github.com/thkl/hap-homematic/assets/30420568/30256703-812e-4215-a489-26d9dac65d3d">

**Comment by thkl** [comment]
Die Namen kommen von HapNodeJs also ja die neuere Version bringt die mit.

**Comment by roe1974** [comment]
nein geht alles ... wenn ich die umbenenne hat das einein impact auf homekit ?

**Comment by ChrWi** [comment]
Ich behaupte mal nein, da HomeKit hier erstaunlich intelligent ist. Hatte das zwischenzeitlich auf beiden Seiten mal gemacht und keine Probleme bekommen. Nimm am besten die Instanz mit den wenigsten Geräten

**Comment by thkl** [comment]
Der Name ist völlig schnuppe. der Schlüssel für HomeKit un zu wissen, welche Instanz was ist, ist die Mac like ID der Instanz. Solange die sich nicht ändert, erkennt HomeKit die Geräte wieder.

**Comment by roe1974** [comment]
Lustigerweise kommen diese Zahlen/Buchstaben im log so nicht vor ... dort stehen die Instanzen richtig ;-)

**Comment by thkl** [comment]
Das is ja auch Wurschd am Ende.  Die Frage ist doch, löst das hap-nodejs Update das Problem mit den Geräten ...

**Comment by roe1974** [comment]
stimmt .... gehe jetzt auf die neue architektur und werde berichten ....
letzte Frage: bei jedem SD Karten Wechsel und dadurch Neuinstallation muss jedesmal HAP-NodeJS manuell hochgezogen werden ... oder änderst Du den installer ?

**Comment by roe1974** [comment]
brauche noch ... muss meine homebridge vorher auch noch hochziehen :-/

**Comment by hardl1** [comment]
Mit Interesse habe ich Euere Posts verfolgt und würde auch gerne testen.
Aber leider scheinen meine Kenntnisse nicht auszureichen.
Ich finde nicht einmal den Speicherort "usr/local........".
Da ich die RaspberryMatic auf einer QNAP-VM betreibe, habe ich dort alles abgesucht, ohne Erfolg.s
Wenn ich es richtig verstanden habe, ist die Node JS auf der RaspberryMatic ja auch aktuell.

Auch mit IOS 16.5 funktioniert alles, bis auf das Problem, dass der Türschlossensor HmIP-DLS nicht in HAP-Homematic gefunden wird.

**Comment by california444** [comment]
@roe1974 warst du erfolgreich mit dem Update von npm und hapNodeJs?

**Comment by california444** [comment]
@roe1974 warst du erfolgreich mit dem Update von npm und hapNodeJs?

**Comment by ChrWi** [comment]
@roe1974 Wie siehts aus?

**Comment by roe1974** [comment]
kann geschlossen werden 😉

**Comment by ChrWi** [comment]
Lass uns bei Bedarf mit #694 bzgl. hapnode weitermachen
