### ISSUE TITLE
homematic sensor installation geht nicht

### ISSUE THREAD

**Issue by klaus-schutz** [thkl/hap-homematic#643]
Hallo,

ich habe eine Neuinstallation meiner CCU3 durchgefuehrt und hap-homematic installiert. Leider kann ich keine homematic Sensoren installieren (cuxd shelly Schalter sind ok). Ich sehe im logfile eine Reihe diverser Fehler, wie z.b. die unten. Sieht so aus, als ob eine alte Version von nodejs laeuft, die mit der neueren Syntax nicht zurecht kommt.  Ich habe - nur zum Testen - die 'Fehler' beseitigt, um zu sehen, wie weit ich komme. Natuerlich ist die 'Korrektur' nicht die Richtige, aber nach der 'Korrektur' laufen die Sensoren. Ich hoffe, dass Du helfen kannst, die richtige Korrektur zu machen. 

Vielen Dank und liebe Gruesse,
Klaus

[Thu Aug 10 2023 15:00:11 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize Main Center Door - Sensor Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};
                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)

[Thu Aug 10 2023 15:07:56 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize Main Center Door - Sensor Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts.headers ?? {};
                                          ^

SyntaxError: Unexpected token ?
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)

**Comment by typedown** [comment]
Hallo Zusammen, habe ebenfalls alle Sensoren verloren seit kurzem. Türkontakte und Bewegungsmelder lassen sich nicht mehr mit HAP-Homematic als HomeKit Accessoires einrichten.  Hat jemand eine Lösung gefunden? Danke

**Comment by klaus-schutz** [comment]
Ja, ich habe einen ‘work-around’. Es sieht so aus, dass bei der Installation oder einem Update (der ccu oder eines anderen Modules) eine Reihe von neuen NPM Modulen geladen werden, die eine neuere Version von Java Script brauchen (dieses wird aber nicht installiert). Das Resultat ist, dass diese Module eine Reihe von Laufzeitfehlern ausloesen, wenn man Kontakte oder Bewegungsmelder verwendet. 

Die ‘Korrektur' erfordert, dass man sich ein wenig mit ssh und vi auskennt, da man auf diese Weise den Code dieser Module soweit aendern kann, dass die Fehler nicht mehr auftreten. Ich muss nochmal darauf hinweisen, dass es wirklich nur ein work-around ist und keine saubere Loesung (aber es funktioniert danach alles - soweit ich das sagen kann)

Also, hier der work-around. Anmeldung an der ccu via ssh ist notwendig (ssh ***@***.***). Danach die folgenden Module via vi aendern
1:
/usr/local/addons/hap-homematic/node_modules/agent-base/dist/helpers.js:32 (Zeile 32)
    for await (const chunk of stream) -> await loeschen
2:
/usr/local/addons/hap-homematic/node_modules/agent-base/dist/index.js:102
        return (this[INTERNAL].protocol ?? -> ?? loeschen
3:
/usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {}; -> erstes ? loeschen und ?? {}; loeschen

Das ganze bitte in Eigenverantwortung aendern. Ich kann keine Verwantwortung uebernehmen, wenn diese (suboptimale) Loesung irgendwelche anderen Seiteneffekte hat. 

Werde mich, wenn ich die Zeit finde, mit einer korrekten Loesung beschaeftigen. 

Hier ein Link zu vi: https://www.thegeekdiary.com/basic-vi-commands-cheat-sheet/

Gruesse,
Klaus

⏤⏤⏤⏤⏤

On 13 Aug 2023, at 20:40, Benjamin Fischer ***@***.***> wrote:


Hallo Zusammen, habe ebenfalls alle Sensoren verloren seit kurzem. Türkontakte und Bewegungsmelder lassen sich nicht mehr mit HAP-Homematic als HomeKit Accessoires einrichten. Hat jemand eine Lösung gefunden? Danke

**Comment by blackbasket** [comment]
Das klingt ganz nach altem nodejs... was nutzt ihr genau als CCU-Derivat? Welche nodejs-Version läuft da?

**Comment by klaus-schutz** [comment]
Bei mir laeuft alles auf einer CCU3. Ich denke, dass eine Korrektur auf einer PI einfacher waere, da ich einfach eine neuere Version von nodejs laden wuerde. Ich hatte einfach noch nicht genug Zeit, um zu gucken, wie ich eine neuere Version auf der CCU laden kann und / oder ob ich dem HomeKit eine ‘locale’ Version geben kann. 

npm version liefert dieses Ergebnis auf der ccu3 - node ist wirklich schon ‘was' aelter.

{ npm: '5.6.0',
  ares: '1.14.0',
  http_parser: '2.8.1',
  modules: '57',
  napi: '3',
  nghttp2: '1.32.0',
  node: '8.11.4',
  openssl: '1.0.2p',
  uv: '1.22.0',
  v8: '6.2.414.54',
  zlib: '1.2.11' }

⏤⏤⏤⏤⏤

On 13 Aug 2023, at 22:53, blackbasket ***@***.***> wrote:


Das klingt ganz nach altem nodejs... was nutzt ihr genau als CCU-Derivat? Welche nodejs-Version läuft da?

**Comment by blackbasket** [comment]
Ja, da kommt es auch her... geht auf CCU3 leider nicht zu updaten...

**Comment by klaus-schutz** [comment]
Wenn das nicht geht, dann werde ich mal nach einer guten Moeglichkeit suchen, aeltere Versionen der 'lokal dependencies' zu installieren. 


⏤⏤⏤⏤⏤

On 13 Aug 2023, at 23:06, blackbasket ***@***.***> wrote:


Ja, da kommt es auch her... geht auf CCU3 leider nicht zu updaten...

**Comment by roe1974** [comment]
Warum keine Raspberrymatic auf der CCU3 laufen lassen ... dann sind diese ganzen Probleme weg ;-)

**Comment by klaus-schutz** [comment]
Nun, reine Unwissenheit. Ich habe die CCU3 erst seit kurzer Zeit. Danke fuer den Hinweis. Ich werde es ausprobieren. 

⏤⏤⏤⏤⏤

On 14 Aug 2023, at 09:41, Richard ***@***.***> wrote:


Warum keine Raspberrymatic auf der CCU3 laufen lassen ... dann sind diese ganzen Probleme weg ;-)

**Comment by blackbasket** [comment]
Es kann durchaus Argumente für das Original-Build geben ;) Da eq3 so immer sagen wird, das wird nicht supported. Allerdings gilt das schon durch den Einsatz irgendwelcher Zusatzsoftware. HAP, CuXD etc... also ist vermutlich weniger als 1% der vorhandenen CCUs "supported" ;)

**Comment by klaus-schutz** [comment]
Ich habe das aktuelle build der Raspberrymatic installiert. Ging fast, wie beschrieben. Ich musste nur mein Backup manuell laden, da ich schon eine neuere Version des Original OS geladen hatte und die Restore UI sich ueber die neuere build Nummer meines Backups beschwert hat. War aber kein Problem. Laeuft alles, wie geschmiert und die Probleme haben sich erledigt. Ich habe nun eine node version, die den JS code ohne Syntax Fehler verdaut. Danke fuer die Empfehlung.

Grüsse,
Klaus 

⏤⏤⏤⏤⏤

On 16 Aug 2023, at 10:14, blackbasket ***@***.***> wrote:


Es kann durchaus Argumente für das Original-Build geben ;) Da eq3 so immer sagen wird, das wird nicht supported. Allerdings gilt das schon durch den Einsatz irgendwelcher Zusatzsoftware. HAP, CuXD etc... also ist vermutlich weniger als 1% der vorhandenen CCUs "supported" ;)

**Comment by marco74hh** [comment]
Moin, das gleiche Problem tritt auch bei einer frischen Installation von piVCCU auf.
Auch da konnte ich es auf eine veraltete node Version zurückführen, die ich aber nicht recht aktualisiert bekommen habe.
remount filesystem als RW gemacht. npm -g update npm ging noch, aber npm -g update node hat nur Fehler geschmissen.
Kann leider nicht auf Raspberrymatic wechseln, da auf dem pi auch Homebridge, InfluxDB, Grafana, evcc läuft.
Oder kann man Raspberrymatic in einem Container laufen lassen?

Errorlog:
[Wed Aug 16 2023 19:07:38 GMT+0200 (CEST)] info - [HAP Server] [Server] service used for Aussentemp:1 is HomeMaticHumidityAccessory
[Wed Aug 16 2023 19:07:38 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize Aussentemp:1 Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};
                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)

**Comment by roe1974** [comment]
ja ... geht auch als Docker:

https://github.com/jens-maus/RaspberryMatic/wiki/Installation-Docker-OCI

**Comment by marco74hh** [comment]
Ja, mit Docker und RaspberryMatic funktioniert alles wie gedacht. Aber eigentlich schade, da die Lösung mit pivccu auf mich schlanker wirkt, da ich docker für nichts anderes benötige.

**Comment by roe1974** [comment]
es gibt ja noch andere virtuelle Möglichkeiten ;-)
<img width="358" alt="Bildschirmfoto 2023-08-17 um 09 15 08" src="https://github.com/thkl/hap-homematic/assets/30420568/63ee8fd7-33cc-4303-8dca-347c550e59eb">

**Comment by ChrWi** [comment]
Habe gestern meine pivccu , zuvor 3.69, auf 3.71 aktualisiert und weiterhin keinerlei Probleme mit meinen Sensoren (Bewegungsmelder habe ich nicht). Woran kann das liegen? 
P.S. Mein nodejs ist natürlich auf 8.11.4 (siehe auch #621)

**Comment by blackbasket** [comment]
Seid wann existieren die Sensoren bei dir in HAP @ChrWi ?

**Comment by ChrWi** [comment]
SWDO: ca 2016 und 2019
SWDM-2 seit Mai 2023

**Comment by ChrWi** [comment]
Was machen wir jetzt hier? Wüsste nicht, was @thkl hier tun könnte

**Comment by aboesener** [comment]
Ja hallöchen, ich bin noch relativ neu in dieser Welt und wollte nun auch die ersten beiden Fensterkontakte hinzufügen. Leider vergebens. Der Letzte Beitrag ist nun schon fast 8 Monate her. Daher die kurze Frage: Gibt es hier was neues?

**Comment by ChrWi** [comment]
Was ist Deine CCU Basis @aboesener ?

**Comment by aboesener** [comment]
Hi @ChrWi, ich habe eine CCU3 von Homeatic mit der aktuellen Firmware 3.77.6. 

(Ich hoffe, dass wolltest du wissen. Hab extra nen Freund gefragt, der von der Materie mehr Ahnung hat. 😅)

**Comment by ChrWi** [comment]
Ok, gibt ja mehrere Möglichkeiten (siehe Kommentar von @roe1974 ) und scheinbar gibt es hier immer wieder (oder mehr) Probleme. Ich nutze eine pivCCU mit der 3.77.6 auf einem Raspberry und habe seit langem keine Probleme mit dem Plugin.

**Comment by ChrWi** [comment]
Siehe #706
