### ISSUE TITLE
A number of window sensors and light switches lead to errors in log-file and don't show up in Apple Home

### ISSUE THREAD

**Issue by cheinelt** [thkl/hap-homematic#647]
The error happens always in same line (see log-file output below). The result is that the according rooms are not set up correctly and some homematic and homematicIP devices don't show up in Apple Home.

```
[Sat Sep 09 2023 12:45:37 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize Wohnzimmer INT0000002:2 Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};
                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)
```

I'm running latest piVCCU 3.71.12-85 on latest raspbian (bullseye) with latest HAP-HomeMatic 0.0.14.

**Comment by ChrWi** [comment]
Same as #648

**Comment by AxLub** [comment]
Hallo,
ich habe das gleiche Problem wie Cheinelt auch meine Log-Datei zeigt genau das gleiche an.
Ich bin erst neu hier und leider hab ich die Lösung hier nicht gefunden.
Vielleicht können wie mir helfen meine beiden Fensterkontakte in die Homekit zu überführen.
Danke...
