### ISSUE TITLE
HMIP-SWO-PR in HomeKit einbinden - Einstellungen in hap-homematic werden nicht übernommen

### ISSUE THREAD

**Issue by foxone85** [thkl/hap-homematic#653]
Hallo zusammen

Erst einmal besten Dank für die Bereitstellung dieses Addons für die Homematic CCU3.
Ich habe die Einrichtung von hap-homematic wie in der Beschreibung und Tutorial durchgeführt.
Die Instanzen sind erstellt und die Bridge auch in Homekit hinzugefügt. In der CCU Systemsteuerung sin die Ports 9874-9878 freigegeben.
Wenn ich nun in hap-homekit den Kanal für die Wetterdaten der Weather Station Pro auswähle und bestätige gelange ich nur wieder auf den homescreen, welcher aber shaded ist und ich keine weiteren Aktionen druchführen kann. Ich muss die ganze Seite wieder neu laden. Sämtliche Einstellungen (Geräte etc.) wurden nicht gespeichert und der Einrichtungsassistent erscheint wieder. Was mache ich falsch?
Die Log Datei besagt folgendes:

[...]
[Thu Oct 05 2023 09:15:21 GMT+0200 (CEST)] info - [HAP Server] [Server] service used for HmIP-SWO-PR 00185F299965E9:1 is HomeMaticWeatherStationAccessory
**[Thu Oct 05 2023 09:15:21 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize HmIP-SWO-PR 00185F299965E9:1 Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};**
                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)

[...]

Ich danke euch für die Hilfe und Unterstützung.

**Comment by foxone85** [comment]
@ChrWi Benutze lediglich die CCU3 in Verbindung mit der Wetterstation HmIP-SWO-PR. Die CCU3 läuft auf der aktuellsten Firmware 3.71.12.

lg

**Comment by ChrWi** [comment]
Kannst Du bitte mal die Einstellungen (unter Internes) teilen?.

**Comment by foxone85** [comment]
Hi

"Internes" gibts leider nicht als Menüpunkt. Aber das sollten die beiden wichtigen Seiten sein für die Einbindung der CCU3 im Netzwerk

![image](https://github.com/thkl/hap-homematic/assets/147033571/45e9ca89-d04e-4a7f-a8b3-8e73a119066b)
![image](https://github.com/thkl/hap-homematic/assets/147033571/2937f903-193f-4642-80a5-0400abeccdeb)

**Comment by foxone85** [comment]
Sorry, du meintest im Add-In ;-) et voilà

![image](https://github.com/thkl/hap-homematic/assets/147033571/5c5ebd36-becc-4f18-af08-526f9a1b90ab)

**Comment by ChrWi** [comment]
Nimm die https Einstellung bitte raus und starte den HAP Service danach neu (letzter Eintrag unter Internes).
Sofern Du nur Apple Home nutzt, kannst Du auch Apple Home-App kompatibel aktivieren. Das sollte aber nichts mit deinem Problem zu tun haben.

**Comment by foxone85** [comment]
Wenn ich die Apple Home-App kompatibel Option selektieren funktioniert es. Ich sehe jedoch nur Temperatur, Feuchtigkeit und Lux wert. Regen, Regenmenge, Windstärke und richtung fehlen komplett, da diese Werte bekanntlich nicht von Apple Home unterstützt werden. 
Die Frage ist nun warum es nur so funktioniert? Hat der Dienst HomeMaticWeatherStationAccessory irgend ein Problem mit den anderen Werten?

LG

**Comment by ChrWi** [comment]
Interessant- ich hatte auf https getippt, da eine Zeile im Log oben darauf hindeutet.
Ansonsten als Tipp: ich nutze accuweather für Wetterdaten und schreibe die gewünschten Werte in Variablen (https://homematic-forum.de/forum/viewtopic.php?f=18&t=59370) Diese können dann zB als Feuchtigkeit angezeigt werden. Windgeschwindigkeiten größer 36kmh aktivieren den Rauchsensor. 
![IMG_0648](https://github.com/thkl/hap-homematic/assets/52505025/986a9edb-46d5-43e1-9f78-a75905c69350)
![IMG_0649](https://github.com/thkl/hap-homematic/assets/52505025/8456b30e-6832-46aa-99c2-e1ae576c19b8)

@thkl Kannst Du die Notwendigkeit der Apple-Kompatibilität für die Wetterstation erklären?

**Comment by ChrWi** [comment]
Ich referenziere auf eine ältere Beschreibung von @thkl : https://github.com/thkl/hap-homematic/issues/37#issuecomment-626390778

**Comment by foxone85** [comment]
Besten Dank für die Inputs.
Für meine Anwendung im Eigenheim bin ich leider auf Echtzeit-Daten angewiesen und nicht auf Vorhersagen wie bei accuweather. Im Genauen brauche ich Echtzeit Regensensor- und Wind-Meldungen, welche mit einen Alarm auslösen und als Automations-Regel die Markiesen einfahren (bspw.).
Ich verstehe das Problem noch nicht ganz, weshalb das Add-In nur mit der Apple Home-Kit Kompatibilität funktioniert. In der Eve App könnte ich eben auch Regenmenge und Windstärke als Variablen für eine Automation nutzen. Bei HomeKit ist das ja noch nicht möglich.

LG
