### ISSUE TITLE
HAP stürzt kurz nach Start ab

### ISSUE THREAD

**Issue by iuliusmaximilian** [thkl/hap-homematic#659]
Nachdem einige Variablen in der CCU3 3.71.12 angelegt und gelöscht wurden, startet HAP HM nicht mehr. HAP HM startet kurz, und stürzt dann komplett ab. Im Debug Modus kommt folgender Error je Variable:

```
[Fri Nov 03 2023 13:29:49 GMT+0100 (CET)] [HAP Server] [Rega] RegaScript object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('PVFullPowerMode');if (o){Write(o.State());}
...
[Fri Nov 03 2023 13:29:49 GMT+0100 (CET)] [HAP Server] [Rega] Error Error: connect EMFILE 127.0.0.1:8181 - Local (undefined:undefined)while executing rega script object o = dom.GetObject(ID_SYSTEM_VARIABLES).Get('PVFullPowerMode');if (o){Write(o.State());}
...
(node:2481) UnhandledPromiseRejectionWarning: Error: connect EMFILE 127.0.0.1:8181 - Local (undefined:undefined)
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at internalConnect (net.js:960:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:284:19)
    at net.js:1058:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:2481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iuliusmaximilian** [comment]
Backup von HAP HM einspielen hat nichts geholfen, Backup der CCU 3 einspielen hat es gelöst.
