### ISSUE TITLE
HMIP-MOD-HO lässt sich nicht hinzufügen

### ISSUE THREAD

**Issue by DeJaZa** [thkl/hap-homematic#661]
Hallo,
wenn ich versuche meinen Garagentoröffner HMIP-MOD-HO hinzuzufügen taucht dieser nicht auf.
In der config.json steht er drin.
Laut log scheint es hier in einen Fehler zu laufen wenn versucht wird das Modul hinzuzufügen.

`[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] loading devices for instance b6589fc6-ab0d-4c82-8f12-099d1c2d40ab
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] try find serviceclazz for 00241A499DE20E:1
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] service HomeMaticGarageDoorOpenerAccessory found thru address 00241A499DE20E:1
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] try adding Garagentor to bridge b6589fc6-ab0d-4c82-8f12-099d1c2d40ab
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Garagentor is HomeMaticGarageDoorOpenerAccessory
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E creating homekit accessory Garagentor
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E publishing services for Garagentor
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E buildAddress PROCESS
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E seems to be a single datapoint
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] register address HmIP-RF.00241A499DE20E:1.PROCESS for events
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] ask Rega HmIP-RF.00241A499DE20E:1.PROCESS
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('HmIP-RF.00241A499DE20E:1.PROCESS');if (o){Write(o.Value());}
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E buildAddress DOOR_STATE
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E seems to be a single datapoint
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] register address HmIP-RF.00241A499DE20E:1.DOOR_STATE for events
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] ask Rega HmIP-RF.00241A499DE20E:1.DOOR_STATE
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('HmIP-RF.00241A499DE20E:1.DOOR_STATE');if (o){Write(o.Value());}
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E adding ventilation
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E enable logging service  door for Garagentor
[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] error - [HAP Server] Unable to initialize Garagentor Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
        this.proxyHeaders = opts?.headers ?? {};
                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)
`

**Comment by schoe-to** [comment]
> Hallo,
> 
> wenn ich versuche meinen Garagentoröffner HMIP-MOD-HO hinzuzufügen taucht dieser nicht auf.
> 
> In der config.json steht er drin.
> 
> Laut log scheint es hier in einen Fehler zu laufen wenn versucht wird das Modul hinzuzufügen.
> 
> 
> 
> `[Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] loading devices for instance b6589fc6-ab0d-4c82-8f12-099d1c2d40ab
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] try find serviceclazz for 00241A499DE20E:1
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] service HomeMaticGarageDoorOpenerAccessory found thru address 00241A499DE20E:1
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Server] try adding Garagentor to bridge b6589fc6-ab0d-4c82-8f12-099d1c2d40ab
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] info - [HAP Server] [Server] service used for Garagentor is HomeMaticGarageDoorOpenerAccessory
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E creating homekit accessory Garagentor
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E publishing services for Garagentor
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E buildAddress PROCESS
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E seems to be a single datapoint
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] register address HmIP-RF.00241A499DE20E:1.PROCESS for events
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] ask Rega HmIP-RF.00241A499DE20E:1.PROCESS
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('HmIP-RF.00241A499DE20E:1.PROCESS');if (o){Write(o.Value());}
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E buildAddress DOOR_STATE
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E seems to be a single datapoint
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] register address HmIP-RF.00241A499DE20E:1.DOOR_STATE for events
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [CCU] ask Rega HmIP-RF.00241A499DE20E:1.DOOR_STATE
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [Rega] RegaScript object o = dom.GetObject('HmIP-RF.00241A499DE20E:1.DOOR_STATE');if (o){Write(o.Value());}
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E adding ventilation
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] debug - [HAP Server] [HomeMaticGarageDoorOpenerAccessory] 00241A499DE20E enable logging service  door for Garagentor
> 
> [Thu Nov 16 2023 11:50:11 GMT+0100 (CET)] error - [HAP Server] Unable to initialize Garagentor Error is /usr/local/addons/hap-homematic/node_modules/https-proxy-agent/dist/index.js:54
> 
>         this.proxyHeaders = opts?.headers ?? {};
> 
>                                  ^
> 
> 
> 
> SyntaxError: Unexpected token .
> 
>     at createScript (vm.js:80:10)
> 
>     at Object.runInThisContext (vm.js:139:10)
> 
>     at Module._compile (module.js:616:28)
> 
>     at Object.Module._extensions..js (module.js:663:10)
> 
>     at Module.load (module.js:565:32)
> 
>     at tryModuleLoad (module.js:505:12)
> 
>     at Function.Module._load (module.js:497:3)
> 
>     at Module.require (module.js:596:17)
> 
>     at require (internal/module.js:11:18)
> 
>     at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:27:29)
> 
> `

Habe das gleiche Problem.

**Comment by ChrWi** [comment]
Ich gehe von node Problemen aus - diese Art Fehlermeldungen gibt es auch in anderen Beiträgen dazu. Die Apple Kompatibilität macht da Einschränkungen, die nur @thkl im Detail erklären kann

**Comment by DeJaZa** [comment]
Es hat tatsächlich Abhilfe geschafft, vielen Dank.
Nun könnte ich endlich (theoretisch) mein Garagentor aus dem Auto heraus öffnen, Musste jetzt aber leider feststellen, dass ich dafür schon im WLAN sein muss. Das ist ja leider bei der Anfahrt nicht unbedingt der Fall. Dass sich ein weiteres Device wie mein iPad zu Hause befindet ändert daran leider nichts. Auch einen VPN Tunnel nach Hause aufbauen hilft nicht um die Homekit Geräte zu bedienen :/

**Comment by ChrWi** [comment]
Was nutzt Du als Apple Home Basis? Zugriff von extern (5G) muss möglich sein, sonst macht Smarthome für mich auch keinen Sinn, insb. für Zugriff auf Sicherheitsgeräte

**Comment by DeJaZa** [comment]
Ich habe sonst keine "Basis". Aktuell nur die HAP-Homematic Installation auf der CCU.

**Comment by ChrWi** [comment]
Ach so. Aber wozu dann HAP-Homematic? Apple TV oder Homepod (nutze ich) brauchst Du schon, ein iPad wird dafür ab iOS16.? nicht mehr unterstützt
