### ISSUE TITLE
HAP unresponsive - mehrere Fehlercodes

### ISSUE THREAD

**Issue by XinXed** [thkl/hap-homematic#683]
**Please describe your problem**
verschiedene Sensoren scheinen zu Problem zu führen. 
Hier im spezifischen:
HMIP-PS (Steckdose)
HmIP-FSM (Unterputz Schalter)

**What happends**
HAP reagiert auf keine Befehle/Änderungen mehr. Neue Geräte können nicht hinzugefügt werden- Instanzen nicht publik gemacht werden

**Steps to reproduce this issue**
sobald eines dieser Geräte hinzugefügt wird, scheint alles irgendwie zu "haken".
ich habe hab komplett neu aufgesetzt und sofort wieder den gleichen Fehler nach Wizard.
hier sind die Logs dazu

**Steckose hinzugefügt nach "fresh and clean setup"**
`[Wed May 01 2024 01:32:01 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize HMIP-PS 00021D899996BD:3 Error is /usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:250
    async *getMultipartRequest(multipartOptions, boundary) {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/index.js:16:18)
`
**Hier der Unterputz Aktor der die erste Config zerschossen hat:**

`[Wed May 01 2024 00:44:34 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize HmIP-FSM 00089A499F8958:2 Error is /usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:250
    async *getMultipartRequest(multipartOptions, boundary) {
          ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/index.js:16:18)
[Wed May 01 2024 00:44:34 GMT+0200 (CEST)] info - [HAP Server] [Server] service used for HmIP-FSM 00089A499F8958:3 is HomeMaticProgrammableSwitchAccessory
[Wed May 01 2024 00:44:34 GMT+0200 (CEST)] error - [HAP Server] Unable to initialize HmIP-FSM 00089A499F8958:3 Error is /usr/local/addons/hap-homematic/node_modules/gaxios/build/src/gaxios.js:250
    async *getMultipartRequest(multipartOptions, boundary) {`

**Comment by jb-home** [comment]
Wie sind denn die Namen der Aktoren in der CCU?
Hast du da Sonderzeichen drin?

**Comment by XinXed** [comment]
Danke ich werde drauf achten.. jetzt habe ich grade eine stabile Instanz laufen. jetzt werde ich Gerät für Gerät hinzufügen und schauen!
Werde auch äöü vermeiden - ich melde mich!

**Comment by XinXed** [comment]
ok also jetzt mal wieder Zeit gehabt. es läuft alles 100% perfect.
Update auf die letze Version der Rasberry Matic und JEDES Sonderzeichen konsequent vermieden.
Ich vermute, dass es evtl auch an den Namen der Instanzen / Räume gelegen haben könnte da diese (warum auch immer) in meinem Patch vor Rasberry Matic teilweise Namen hatten wie room:{garden} oder so. (es schien eine variable zu sein die je nach anmeldung/browser language in anderen sprachen übersetzt - was hier nicht funktioniert hat)

**Comment by ChrWi** [comment]
Danke fürs Feedback!
