### ISSUE TITLE
Homematic Fensterkontak über HAP Homematic in Homekit intigrieren 

### ISSUE THREAD

**Issue by AxLub** [thkl/hap-homematic#706]
Hallo,
leider kann ich keinen Fensterkontakt von Homematic ip in homekit sichbar machen. Ich weisse zwar den Fensterkontakt bei HAP Homematic einem Raum zu er speichert diesen auch. Nur leider wird es am Ende nicht übernommen.

Könnte mir bitte einer Helfen und eine Lösung dazu geben.

Vielen Dank

**Comment by blackbasket** [comment]
Hi @AxLub 

Hast du das Problem ausschließlich mit HmIP TFKs?

LG,
Marcel

**Comment by AxLub** [comment]
Hi Marcel,
ich habe das aktuell nur bei den Fensterkontakten, 
HmIP-SWDO-2
HmIP-SWIDO-I

**Comment by blackbasket** [comment]
Hmm... in der gleichen Instanz sind also schon andere Geräte publiziert und funktionieren? Was genau sind deine Schritte?

**Comment by AxLub** [comment]
Ich habe einen CCU3 da ist das Programm für HAP Homematic installiert. Habe über die HAP Oberfläche die HmIP Geräte den Räumen zu geordnet. Rollladenaktoren und Heizkörperthemostat fünktionieren in Homekit. Ich hatte hier gesehen das dieses Problem schon gab oder gibt mit den Fensterkontakten. Leider konnte ich nicht genau erkennen was die Lösung ist.

**Comment by blackbasket** [comment]
Hast du mal versucht einen TFK in einer neuen Instanz zu veröffentlichen?

**Comment by AxLub** [comment]
Ich habe bei den Instanzen und bei der CCU3 die Räume mal geändert. Leider hat es trotzdem nicht funktioniert. 

Es wurde hier schon mal über das Problem geschrieben # 647 oder # 648

**Comment by Stephan22ST** [comment]
Du hast auch exakt dieselbe Fehlermeldung? Oder etwas anders? Am besten postest du deine hier mal rein... Damit man dir auch direkt hilft und nicht doch an etwas anderem. Nur Sicherheitshalber....

**Comment by Stephan22ST** [comment]
Ansonsten, wenn du sicher bist, dass dein Problem dasselbe ist, dann sollte dir das hier helfen:
https://github.com/thkl/hap-homematic/issues/643#issuecomment-1676458971

Es ist einfach ein Problem, dass die CCU3 im Originalen halt ziemlich veraltet ist. RaspberryMatic ist da etwas besser aufgestellt. Deshalb habe ich auch die Probleme mit denselben Kontakten nicht. Bei mir klappt es nämlich.

Ältere Versionen könnten halt kein ?? und ? als optional...

Anders wüsste ich auch nicht wie du das hinbekommst... 

Aber auch ich kann dir nicht sagen, welche Auswirkungen diese Änderungen haben. Deshalb auf eigene Verantwortung und mit etwas Vorsicht zu genießen. Denn das entfernen von ?? und ? hat halt - naja - schon was zu bedeuten ;-)

**Comment by AxLub** [comment]
Hallo Stephan, erstmal vielen Dank für deine Rückmeldung. 
Also es gibt nicht wirklich einen Fehlermeldung. Ich such in der Hap-Homematic das gerät raus - suche den passenden Service- dann die HAP Instanz - er versucht zu speichern aber es ist nicht wie bei den anderen. Man findet das gerät wieder unter Neu und man müsste es wieder neu hinzufügen.

**Comment by AxLub** [comment]
Hier hab ich mal das Log heruntergeladen. Leider kenne ich mich damit nicht wirklich aus.

Für die eine funktion sind noch viel mehr in der Log Datei. 

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/index.js:31:18)

**Comment by blackbasket** [comment]
Welche nodejs-Version läuft denn eigentlich inzwischen auf einer CCU3 mit Original-FW?

**Comment by AxLub** [comment]
Aktuelle Firmwareversion:  3.79.6

nodejs-Version - Was ist damit gemeint?

**Comment by Stephan22ST** [comment]
> Hier hab ich mal das Log heruntergeladen. Leider kenne ich mich damit nicht wirklich aus.
> 
> Für die eine funktion sind noch viel mehr in der Log Datei.
> 
> SyntaxError: Unexpected token * at createScript (vm.js:80:10) at Object.runInThisContext (vm.js:139:10) at Module._compile (module.js:616:28) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object. (/usr/local/addons/hap-homematic/node_modules/gaxios/build/src/index.js:31:18)

Dann hast du nicht das Problem aus den zwei Beiträgen die du verlinkt hast, sondern eher folgendes Problem:
https://github.com/thkl/hap-homematic/issues/704

**Comment by blackbasket** [comment]
> Aktuelle Firmwareversion:  3.79.6
> 
> nodejs-Version - Was ist damit gemeint? 

Es wäre hilfreich, wenn du die Suchfunktion selbst nutzt ;)

Per SSH:
`node --version`

**Comment by AxLub** [comment]
> > Aktuelle Firmwareversion: 3.79.6
> > nodejs-Version - War ist das Selbstbetensen?
> 
> Es en-du-sterben Suchfunktion selbst ;)
> 
> Per SSH: `node --version`

Leider weiß ich nicht was du damit meinst.?

**Comment by AxLub** [comment]
> > Hier hab ich mal das Log. Leider kenne ich mich nicht aus.
> > Für die funktion und einem sind mehr in der Log Datei.
> > SyntaxError: Unerwartetes Token * bei createScript (vm.js:80:10) bei Object.runInThisContext (vm.js:139:10) am Modul.compile (module.js:616:28) an Object.Module.-extensions.js (module.js:663:10) am Modulload (Modul.js:565:32)js:497:3) bei Module.require (module.js:596:17) nach Bedarf (intern/module.j.js:11:18) bei Object. (/usr/local/addons/hap-homematic/node-modules/gaxios/build/src/index.js:31:18)
> 
> Dann hast nicht du das Problem aus der zwei Beiträgen die verlinkt, [704 US-Dollar](https://github.com/thkl/hap-homematic/issues/704)

Hi Stephan, 
was heißt das für mich jetzt.

Was heißt das jetzt für mich. Ich bin leider nicht so ein Kenner der Irgendwas programmiert oder umschreiben kann.

Vielen Dank schon mal für deine Unterstützung.

**Comment by Stephan22ST** [comment]
Ich befürchte aus diesem Grund, dass du daran nichts ändern kannst. Das hier wird von niemanden weiter entwickelt oder gewartet. Und ohne ein wenig Kenntnis was ssh ist und was

node —version

bedeutet, wird es halt leider echt fast unmöglich.

tut mir leid

**Comment by Stephan22ST** [comment]
Du könntest lediglich auf RaspberryMatic wechseln und gucken ob deine Probleme damit weg sind.

Bei mir klappt es super, aber mit RaspberryMatic

aber auch dafür musst du einiges tun ohne vorher zu wissen ob es für dich klappt und mit Risiken verbunden, dass irgendwelche Sachen fehlen die du früher hattest. Was du alles neu machen musst. Aber das passiert i.d.r. nicht, ist aber möglich.

Oder du nimmst RedMatic für die CCU3 und installierst in RedMatic dann HomeKit-HomeBridge.

Dann musst du HAP aber löschen. Das übernimmt dann HomeBridge

**Comment by AxLub** [comment]
Stephan kann ich RedMatic zusätzlich auf die CCU3 installieren ? So, dass alle meine Homematic Produkte gleich in der CCU 3 verbleiben.

**Comment by Stephan22ST** [comment]
Ich bin da immer Vorsichtig mit Äußerungen. Es kann halt verdammt viel passieren. Das hab auch ich selber schon merken müssen.

Also vorher ein Backup machen usw. 

Aber dann theoretisch ja. RedMatic installieren über Zusatzprogramme und einfach Geduld haben. Es dauert ne zeitlang bis die CCU3 dann wieder am netz ist. Für gewöhnlich passiert aber nichts und alles läuft wie vorher...

**Comment by AxLub** [comment]
Was ist das eigentlich ? 
Wo könnte man das eintragen oder hinschreiben. Das habe ich bekommen für die Supportanfrage für den jeweiligen Fensterkontakt. 



<html><body>

devices |  
-- | --
0 |  
id | 1000
intf | 0
intfName | ""
name | "HmIP-SWDO-2"
address | "4031644974ABCD"
type | "HmIP-SWDO-2"
channels |  
0 |  
id | 1001
name | "4031644974ABCD:0"
intf | 0
address | "4031644974ABCD:0"
type | "MAINTENANCE"
access | 255
1 |  
id | 1002
name | "4031644974ABCD:1"
intf | 0
address | "4031644974ABCD:1"
type | "SHUTTER_CONTACT"
access | 255
2 |  
id | 1003
name | "4031644974ABCD:2"
intf | 0
address | "4031644974ABCD:2"
type | "ALARM_COND_SWITCH_TRANSMITTER"
access | 255


</body>
</html>

**Comment by AxLub** [comment]
> Ich bin da dü die Vor mit Äußerungen. Es kann halt ü-wüchselte schwing. Das hab nach der merken merken
> 
> Auch vorher ein Backup macht vor.
> 
> Aber dann als ja. RedMatic installieren über Zusatzprogramm und einfach Geduld haben. Es dauert slang ne zeitlang bis die CCU3 am netz ist. Für passiert nichts und alles...

Dafür muss ich aber Homekit auf der CCU3 entfernen oder ?

**Comment by Stephan22ST** [comment]
Ist theoretisch nichtmal notwendig. Es ist einfach ne andere Instanz die gestartet wird. Aber ich würde halt Sachen die ich dann nicht mehr nutze löschen. Da HAP dann ja nichts mehr macht außer da zu sein und Ressourcen zu verbrauchen.

**Comment by Stephan22ST** [comment]
> Was ist das eigentlich ? Wo könnte man das eintragen oder hinschreiben. Das habe ich bekommen für die Supportanfrage für den jeweiligen Fensterkontakt.
> 
> devices |   -- | -- 0 |   id | 1000 intf | 0 intfName | "" name | "HmIP-SWDO-2" address | "4031644974ABCD" type | "HmIP-SWDO-2" channels |   0 |   id | 1001 name | "4031644974ABCD:0" intf | 0 address | "4031644974ABCD:0" type | "MAINTENANCE" access | 255 1 |   id | 1002 name | "4031644974ABCD:1" intf | 0 address | "4031644974ABCD:1" type | "SHUTTER_CONTACT" access | 255 2 |   id | 1003 name | "4031644974ABCD:2" intf | 0 address | "4031644974ABCD:2" type | "ALARM_COND_SWITCH_TRANSMITTER" access | 255

Kann ich dir so ohne zu wissen worum es dem Support da genau ging gar nichts zu sagen. Sieht mir nur aus wie eine Zusammenfassung des Sensors den du hast. So exportiert man z.b. Daten halbwegs leserlich aus Datenbanken. Ob man das irgendwo einspielen kann, kann ich dir nicht beantworten. Wüsste zumindest gerade nicht wofür.

**Comment by AxLub** [comment]
Stephan was ist der Unterschied zwischen RedMatic und RaspberryMatic

**Comment by Stephan22ST** [comment]
RaspberryMatic ist ein alternatives Betriebssystem für die CCU3. Wird einfach gefühlt deutlich aktueller gehalten als das Originale.

RedMatic ist eine Zusatzsoftware die die CCU3 (egal welches Betriebssystem) einfach erweitert...

Aber dazu am besten vorher selber etwas einlesen. Gibt sehr viele Beiträge die sehr aufschlussreich sein können.

**Comment by AxLub** [comment]
ok. Bin schon viel am lesen gewesen die letzten tage.
Kann man RaspberryMatic auf die CCU3 installieren oder braucht man eine andere/eigene Hardware?

**Comment by Stephan22ST** [comment]
Kann auch auf die Originale CCU3 installiert werden. Nur wenn man dann wieder die Originale Firmware drauf haben möchte auf der CCU3 und von RaspberryMatic weg möchte, muss man die SD Karte ausbauen und neu Flashen etc.

**Comment by AxLub** [comment]
Ich habe RedMatic auf der CCU3 und darüber alles in Homekit integriert. Leider werden 2 Produkte nicht gefunden. Ein Heizungsthermostat und ein Fensterkontakt die ich vor 3 Wochen gekauft hatte. Ausserdem wir ein Rolladen in Homekit als zu angezeigt dabei ist er offen.

**Comment by Stephan22ST** [comment]
Schau mal ob du in der Konfiguration von HomeKit alle Häkchen gesetzt hast für die verschiedenen Protokolle.
Als zweites mal schauen ob RedMatic bei der HomeKit Konfiguration diese Geräte anzeigt und auch ob dort die Häkchen gesetzt sind, dass die Übernommen werden sollen.

Wenn auch HomeBridge bei dir nicht läuft.. Dann ist das leider etwas wo du wohl nichts dran ändern kannst, da wie du sagst deine Kenntnisse nicht so wären, dass du eine chance hättest...

Ich z.b. habe eine Sirene die falsch angebunden war. Hab ich halt umprogrammiert und läuft...

Und dein Rollladen der was falsches anzeigt, ist der identisch mit den Rollläden die richtig darstellen? Vom Typ her. Wenn ja, würde ich einfach mal versuchen über HomeKit den zu bedienen. Vielleicht hängt es da einfach irgendwo.

Verschwendung RedMatic zu installieren war es trotzdem nicht. Ich finde das sollte Grundausstattung sein für eine CCU. Da kannst du einfach viel mehr und viel leichter machen. (Persönliche Meinung) :-D

**Comment by AxLub** [comment]
Ich versuche es mal. Danke für deine Hilfe!
Wenn ich RaspberryMatic auf meine CCU3 installiere, wo durch bekomme ich Kontakt zum Homekit?

**Comment by AxLub** [comment]
Leider sehe ich die beiden Homematic ip Geräte noch nicht. Bei Node_RED - Unreach da sehe ich die beiden Geräte ( Fensterkontakt und Heizkörperthermostat) leider weiss ich nicht was man da machen könnte.

**Comment by Stephan22ST** [comment]
Da kann ich dir jetzt so ohne weiteres auch nicht bei helfen. Wenn beide Programme bei dir Probleme machen... Naja ist halt beides letztendlich auch schon etwas älter.. Damit muss man bei HomeKit leben.

RaspberryMatic ist eine alternative Software für die CCU3 mit aktuelleren Versionen. Und von einem anderen Herausgeber. Auf RaspberryMatic verwendest du dann das HAP Homematic hier. Aber ob das dann tadellos bei dir läuft.. Steht halt noch wo anders. Ich kann nur berichten, dass es bei mir klappt. Mehr kann ich halt nicht machen ;-)

**Comment by AxLub** [comment]
Vielen Dank für deine Hilfe Stephan

**Comment by kuestenjunge** [comment]
Moin,
habe ein ähnliches Problem wie @AxLub und mir mal angesehen, welche node.js Version mit aktueller CCU Firmware 3.83.6 auf der CCU3 läuft und war etwas irritiert.
node -v
v8.11.4
@AxLub hast Du Dein Problem mittlerweile lösen können?

**Comment by AxLub** [comment]
Guten Morgen, leider hab ich das Problem immer noch. 
Ich habe mich entschlossen bei der App Pocket Control HM zu bleiben.
